### ISSUE TITLE
`symfony/framework-bundle`: need `Kernel::getProjectDir()` method back

### ISSUE THREAD

**Issue by yannoff** [symfony/recipes#1000]
As of version `5.1` of the recipe, the `Kernel::getProjectDir()` override has been removed in 5d24d659fc54e2ed564ae93f2f09a2fefe0c850f .

While it seems totally legitimate to assume that any *standard* symfony application uses `composer`, it doesn't mean there is necessarily a `composer.json` at the top-level dir of the project.

Here are a few example use-cases:

1. An alternative name, setup using the `COMPOSER` environment variable, for instance:

```bash
/usr/bin/env COMPOSER=dependencies.json composer install
```

2. All composer related files may be situated in a different location, eg:

```bash
.
├── bin
├── config
├── dependencies
│   ├── composer.json
│   ├── composer.lock
│   └── vendor
│       ├── autoload.php
│       └── composer
├── migrations
├── public
├── src
├── templates
├── translations
└── var
```

I know overriding the `Kernel::getProjectDir()` is quite simple, but since the purpose of the recipes is to ease and fasten development of symfony applications, it would be nice to be able to rely on the default implementation of the kernel instead of reinventing the wheel each time we need an application with those kind of custom composer config.

**Comment by derrabus** [comment]
For reference, the PR that removed that override was #705.

**Comment by nicolas-grekas** [comment]
Recipes cover the defaults and most common needs.
If you have specific needs (like when not having a composer.json file), then adding the method explicitly in your Kernel class is the way to go.

**Comment by yannoff** [comment]
@nicolas-grekas I really don't understand the decision to abandon the `dirname(__DIR__)` logic, it worked well :confused: 

Considering that in a common symfony app, `Kernel` is always located in `src/`, it seems to me that most part of the use cases are covered.

Moreover, I have a relevant use-case I came up to recently, I will open a new (sorry, same subject) issue for this.
