### ISSUE TITLE
[phpunit-bridge recipe] Set `APP_DEBUG` to `false` in `phpunit.xml` to speed up the tests

### ISSUE THREAD

**Issue by maks-rafalko** [symfony/recipes#1025]
It was proposed [back in 2019](https://github.com/symfony/recipes/pull/530) by `@javiereguiluz`, but for some reason didn't get enough popularity. Though, now Symfony's documentation mentions this improvement in a ["Set-up your Test Environment"](https://symfony.com/doc/current/testing.html#set-up-your-test-environment) paragraph:

> It is recommended to run your test with `debug` set to `false` on your CI server, as it significantly improves test performance. This disables clearing the cache. If your tests don't run in a clean environment each time, you have to manually clear it using for instance this code in `tests/bootstrap.php`:

```php
// ...

// ensure a fresh cache when debug mode is disabled
(new \Symfony\Component\Filesystem\Filesystem())->remove(__DIR__.'/../var/cache/test');
```

We can live with this "inconvenience", especially with the benefit it gets (example for my project):

```diff
- Time: 04:13.959, Memory: 547.01 MB
+ Time: 02:45.307, Memory: 473.00 MB
```

what do you think to update an official recipe and add the following line to `phpunit.xml.dist` somewhere here:

https://github.com/symfony/recipes/blob/a624d3bf1def68bbd2d542b3a99216c0af090552/symfony/phpunit-bridge/5.3/phpunit.xml.dist#L14

```diff
+ <server name="APP_DEBUG" value="false" />
```

This will help many developers creating _new_ projects to not waste time with functional tests.

Related to:

* https://github.com/symfony/recipes/issues/1024
* https://github.com/api-platform/api-platform/pull/2078

**Comment by GromNaN** [comment]
The advice in the doc refers to CI environments. When running tests locally, it is still very useful to have enable debug mode. Things like updating the cache when the config is modified are not supported with `debug:false`.

**Comment by maks-rafalko** [comment]
> When running tests locally, it is still very useful to have enable debug mode.

Could you please elaborate on that? Concrete examples would be very helpful.

I can quote [myself here](https://maks-rafalko.github.io/blog/2021-11-21/symfony-tests-performance/#set-app-debug-false):

> Besides the speed, there is one more (I think major) benefit of using `APP_DEBUG=false`. Functional tests start responding with `Internal Server Error` rather than with an exception message thrown from the source code.
> 
> This can be a dealbreaker in Symfony projects. I saw a couple of projects, where people used the following code:
> 
> ```php
> # App\Controller\SomeController.php
> 
> throw new ConflictHttpException('There is a conflict between X and Y');
> ```
> 
> asserting in tests that response contains exactly this exception message `There is a conflict between X and Y` in functional tests when `APP_DEBUG=true`, while in fact the response message is `The server returned a "409 Conflict".` with `APP_DEBUG=false`, and test start failing after using `APP_DEBUG=false`.
> 
> Using `APP_DEBUG=false` with functional tests is a *right way* from errors/exceptions points of view and this mimics a real production environment.

So, when you writing tests with `APP_DEBUG=true`, you can think that expected error messages in your tests will be the same on production, while they not.

And if you say `APP_DEBUG=true` is for CI only, then it's impossible to have green tests locally and on CI at the same time, if locally you use `APP_DEBUG=false`.

We are using this approach for a couple of years (API-Platform projects), and to be honest I can find the only 1 thing that less convenient with functional tests - with `APP_DEBUG=false` you need to look into `var/log/test.log` rather than to the PHPUnit output when test fails, but this is not an issue at all, IMO.

**Comment by kbond** [comment]
I recommend this (and #1024) in [Foundry's docs](https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#performance). The key with this one is the clearing of the cache before each test run - easy enough in `tests/bootstrap.php`. This would have to be included when setting `APP_DEBUG=false` IMO.

**Comment by nicolas-grekas** [comment]
I would like to see the impact of https://github.com/symfony/symfony/pull/43616 on the topic before considering this.

**Comment by nelson6e65** [comment]
Hmm… In my case is the opposite for local development. 

By using `APP_DEBUG=true` and refreshing the cache, the result is a little better. But second and consequent run of tests, without the cache it takes a lot more, with difference:

```diff
# First run
-Time: 13.15s
+Time: 13.08s

#Second run
-Time: 1.52s
+Time: 13.06s
```

Disabling debug may be useful for CI environments, but not for local development.

> I'm using [PestPHP](https://pestphp.com).

**Comment by maks-rafalko** [comment]
> Disabling debug may be useful for CI environments, but not for local development.

IMO it's impossible, see [my comment above](https://github.com/symfony/recipes/issues/1025#issuecomment-974899083), you will have different error messages (at least).

> In my case is the opposite for local development.

because I suspect you have too few tests yet. The more tests you have, the longer they take, the more benefit you will get from `APP_DEBUG=false`. Look at our example from my [post](https://maks-rafalko.github.io/blog/2021-11-21/symfony-tests-performance/#set-app-debug-false) where we have thousands of functional tests:

```diff
- Time: 04:13.959, Memory: 547.01 MB
+ Time: 02:45.307, Memory: 473.00 MB
```

---



> I would like to see the impact of [symfony/symfony#43616](https://github.com/symfony/symfony/pull/43616) on the topic before considering this.

any news on this or any ideas on how to (help to) test it?

**Comment by nelson6e65** [comment]
Yes, you are right; with larger number of tests is the ideal.

This case is for specific tests that should run fast. For example, if I filter for an specific test suite, by running a watch of a few related tests in local development when working in a specific feature or creating a test for it, skipping unrelated tests.

Then you can see the results in some seconds while workin on it in your editor. In this case, 13 seconds is a lot of time to wait.

**Comment by maks-rafalko** [comment]
> **There is a way to know in the bootstrap.php if the tests are being filtered or running all of them?** thinking

not sure about PHPUnit's built-in behavior, but we can always use PHP's `$argv` and search there.

Another idea that we used in different ways in our projects - env variables, for example:

```php
# tests/bootstrap.php

// ...
if (!getenv('INFECTION')) {
    $filesystem->remove([__DIR__ . '/../var/cache/test']);
}
```
^ to not clear cache when tests are executed from Infection in multiple threads (helps to clear the cache only once, but not for each thread)

or

```php
# tests/bootstrap.php

// ...
if (!getenv('KEEP_SYMFONY_TEST_CACHE')) {
     $filesystem->remove([__DIR__ . '/../var/cache/test']);
}
```

I understand that it can be not very convenient, but it solves the "issue". And aliasing/adding a wrapper command line to Makefile can simplify the things if needed.

But keep in mind, that even if you run *functional* tests with `--filter`, cache clear can still be needed (e.g. when service definition is updated). 

From my experience, cache clearing is not needed when *unit* tests are executed with `--filter`

**Comment by alexislefebvre** [comment]
> > Disabling debug may be useful for CI environments, but not for local development.
> 
> IMO it's impossible, see [my comment above](https://github.com/symfony/recipes/issues/1025#issuecomment-974899083), you will have different error messages (at least) if you decide to use `debug=false` locally but `debug=true` on CI.

One solution may be to rerun the tests with `APP_DEBUG=1` if they fail on CI.

Something like this:

```bash
phpunit …
return=$?

if [ "$return" -ne 0 ]
then
    APP_DEBUG=1 phpunit …
fi
```

**Comment by kbond** [comment]
What about leaving as is, `debug=true` by default, but adding the following to `tests/bootstrap.php`:

```php
if (false === (bool) $_SERVER['APP_DEBUG'] ?? true) {
    /*
     * Ensure a fresh cache when debug mode is disabled.
     */
    (new Filesystem())->remove(__DIR__.'/../var/cache/test');
}
```

Then, in your CI (or anytime you want to run your entire suite), you'd run:

```
APP_DEBUG=0 phpunit
```

This may not even make sense as I don't have a deep knowledge of the component but could `symfony/runtime` be leveraged here somehow? (/cc @Nyholm)

---

BTW, when running tests with `debug=false` and [paratest](https://github.com/paratestphp/paratest) (to further increase performance when running your entire suite), there is an additional consideration. Here's the snippet from my `tests/bootstrap.php`:

```php
if (false === (bool) $_SERVER['APP_DEBUG'] && null === ($_SERVER['TEST_TOKEN'] ?? null)) {
    /*
     * Ensure a fresh cache when debug mode is disabled. When using paratest, this
     * file is required once at the very beginning, and once per process. Checking that
     * TEST_TOKEN is not set ensures this is only run once at the beginning.
     */
    (new Filesystem())->remove(__DIR__.'/../var/cache/test');
}
```

**Comment by nelson6e65** [comment]
Good idea, @kbond. Thanks for your snippet.

**Comment by nicolas-grekas** [comment]
Resource checking is cached since https://github.com/symfony/symfony/pull/43616 so that this should not be needed anymore.
Please upgrade to 5.4 of course to benefit from it.

**Comment by kbond** [comment]
In 5.4, I'm seeing ~15% speed increase on my test suite when using `APP_DEBUG=false`. On 4.4, this was much more dramatic.

Thinking this option should be documented in a performance section on https://symfony.com/doc/current/testing.html

**Comment by nicolas-grekas** [comment]
This should be profiled, understood, discussed and fixed.
Fixing the symptom is starting from the wrong end IMHO.

**Comment by kbond** [comment]
I don't know, when debug=true, is it not expected that "more stuff is being done" by Symfony/3rd party bundles?

**Comment by nicolas-grekas** [comment]
I guess so too, but then blindly disabling all this is not what I'd call "understanding what happens" :)
