### ISSUE TITLE
PANTHER environments variables installed without panther

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/recipes#1033]
The following environment variables are currently set by the phpunit bridge:

```bash
PANTHER_APP_ENV=panther
PANTHER_ERROR_SCREENSHOT_DIR=./var/error-screenshots
```

Think this env variables should be defined inside `symfony/panther` when panther is installed and not from the phpunit bridge.

**Comment by fabpot** [comment]
If possible, that would be nice indeed.

**Comment by nicolas-grekas** [comment]
This is not possible because those vars should be added to `.env.test`, not to `.env`.
While we could improve this to allow adding to `.env.test`, I don't expect anyone to work on this for 2 variables that don't hurt anything.
Closing therefore.
