### ISSUE TITLE
[GitHub][UX] Use “Unix-like” instead of “*nix”

### ISSUE THREAD

**Issue by alexislefebvre** [symfony/recipes#1036]
A bot add a [comment](https://github.com/symfony/recipes/pull/1026#issuecomment-975550597) to PRs, this comment contains this:

> \# On *nix and Mac

I use Linux for years but I had to search what *\*nix* was.

I suggest to use an simpler word instead:

> \# On Unix-like and Mac

This is the name of the Wikipedia article: https://en.wikipedia.org/wiki/Unix-like

I didn't found where this text was written.

**Comment by OskarStark** [comment]
If it makes things more clear, why not

WDYT @nicolas-grekas ?

**Comment by derrabus** [comment]
Doesn't macOS count as Unix-like as well? 🙃

**Comment by alexislefebvre** [comment]
It may be rewritten to use names of the actual OSes families:

> \# On BSD, Linux and macOS

**Comment by nicolas-grekas** [comment]
The code is here: https://github.com/symfony-tools/recipes-checker/blob/main/src/DiffRecipeVersionsCommand.php
PR welcome
