### ISSUE TITLE
Make the config dir easier to override

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/recipes#104]
In https://github.com/symfony/flex/issues/56 there's a proposal to rename `etc/` to `config/` It has 41 upvotes and 0 downvotes ... but that doesn't mean we'll make that change.

In any case, to make things better for people who *really* want to use `config/` in their apps, why don't we make the config dir easily configurable?

If you review the https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/3.3/src/Kernel.php file, you'll see that `etc/` is hardcoded as a string in several methods. Maybe we can introduce a new method similar to getCacheDir() and getLogDir():

```php
    public function getConfigDir(): string
    {
        return dirname(__DIR__).'/etc';
    }
```

**Comment by Pierstoval** [comment]
I agree, but just to be clear, this should be put in the app Kernel class, not the interface :)

**Comment by fabpot** [comment]
That won't work well with Flex recipes anyway. So, making this kind of names configurable should not be supported.

**Comment by javiereguiluz** [comment]
I thought this was "easy" to implement. The typical recipe does this:

```json
"copy-from-recipe": {
        "etc/": "%ETC_DIR%/"
    },
```

So, `etc/` is only hardcoded for the own recipe contents ... but `%ETC_DIR%` (or `%CONFIG_DIR%` ?) is variable and properly resolved for each project.

**Comment by fabpot** [comment]
But if you make it configurable in a PHP file, there is no way to know which directory is configured.

**Comment by Pierstoval** [comment]
That's why `composer.json`'s extra parameters may contain `flex.etc_dir: 'etc/'` or something similar to support it. Indeed it will need to be set in both `composer.json` **and** the Kernel class, but IMO it's the best way to handle this automatically in Flex

**Comment by fabpot** [comment]
Closing as won't fix. Flex is not that opinionated, but making everything configurable does not make sense to me.
