### ISSUE TITLE
Forcing a consistent locale in phpunit bootstrap.php

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/recipes#1050]
I did stumble today over an inconsistent between my local setup and the CI that `\Locale::getLocale()` was `de_AT` locally and `en` on the `CI`.

I thought maybe it would make sense to add the following to the phpunit bootstrap.php files:

```php
if (class_exists(\Locale::class)) { // not sure if required?
    \Locale::setDefault('en');
}
```

so the locale for the Intl packages (Currencies, Locales, ...) are the same on all in Unit Tests.

**Comment by nicolas-grekas** [comment]
This should be submitted to the phpunit-bridge I guess, where we already do that for setlocale:
https://github.com/symfony/symfony/blob/44db49fb8f6d70c4341120a3f8f1b1a1a0dfa014/src/Symfony/Bridge/PhpUnit/bootstrap.php#L28

PR welcome.
