### ISSUE TITLE
[symfony/framework-bundle] Check if `public` directory exists before doing `assets:install`

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/recipes#1053]
I don't have a `public` directory (using just Symfony Console Commands), and so I'm getting this error on `composer update`:

> Executing script cache:clear [OK]
Executing script assets:install public [KO]
 [KO]
Script assets:install %PUBLIC_DIR% returned with error code 1
!!  [critical] Error thrown while running command "--ansi assets:install public". Message: "The target directory "/.../public" does not exist."
!!                                                                                 
!!    The target directory "/.../public" does not exist.                                                                
!!  
!!  assets:install [--symlink] [--relative] [--no-cleanup] [--] [<target>]
!!  
Script @auto-scripts was called via post-update-cmd

Would it be possible to add a check before executing this line?
https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/5.4/manifest.json#L12

**Comment by stof** [comment]
if you don't have a public directory, I suggest you to remove the `assets:install` script.

**Comment by ThomasLandauer** [comment]
How can I remove this?

**Comment by ThomasLandauer** [comment]
OK, thanks, didn't know that it's so easy! ;-)
Just remove this line:
```json
"assets:install %PUBLIC_DIR%": "symfony-cmd"
```
