### ISSUE TITLE
config/routes/annotations.yaml is gone

### ISSUE THREAD

**Issue by gnumoksha** [symfony/recipes#1076]
After ran `composer recipes:update doctrine/annotations` the following change was made in my project:

![image](https://user-images.githubusercontent.com/696797/164499974-221e9b62-3121-4a4f-b6e0-48ef63d8300b.png)

Causing all my routes to return 404 Not Found.

The [documentation](https://symfony.com/doc/current/routing.html#creating-routes-as-attributes-or-annotations) still says `doctrine/annotations` is required to use annotations.

I think this is related to https://github.com/symfony/recipes/pull/1060

**Comment by gnito-org** [comment]
The route config that was in `config/routes/annotations.yaml` is [now in](https://github.com/symfony/recipes/blob/flex/main/symfony.routing.6.0.json) `config/routes.yaml`.

I think you should just update your `symfony/routing` recipe.
