### ISSUE TITLE
flex.symfony.com is still in the github repository description

### ISSUE THREAD

**Issue by Einenlum** [symfony/recipes#1086]
Since the website is gone, it should be removed.

![Screenshot 2022-05-17 at 11-58-41 symfony_recipes Symfony Recipes Repository](https://user-images.githubusercontent.com/5675200/168785437-8c497d34-c50e-458e-88e3-46b5e611f549.png)

**Comment by nicolas-grekas** [comment]
Good catch, fixed, thanks.
