### ISSUE TITLE
Refactor the Doctrine configuration?

### ISSUE THREAD

**Issue by alexislefebvre** [symfony/recipes#1110]
Here is the current config:

https://github.com/symfony/recipes/blob/f54b694258dfcb356f6c59e2ce1a4c49f3cceae9/doctrine/doctrine-bundle/2.4/config/packages/doctrine.yaml#L26-L42

### Observations
- `result_cache_driver` uses `doctrine.result_cache_pool`: this is consistent
- `query_cache_driver` uses `doctrine.system_cache_pool`: this is surprising
- the pools are in the reverse order of their usage
- the pools are using adapter with unexpected names, I searched and [`cache.app`](https://symfony.com/doc/5.4/reference/configuration/framework.html#app) and [`cache.system`](https://symfony.com/doc/5.4/reference/configuration/framework.html#system) are provided by Symfony, yet I don't understand why queries use `system` and results use `app`?

### Proposal
- rename `doctrine.system_cache_pool` to `doctrine.query_cache_pool`
- reorder the pools
- use only one type of storage in the pools

```diff
diff --git a/doctrine/doctrine-bundle/2.4/config/packages/doctrine.yaml b/doctrine/doctrine-bundle/2.4/config/packages/doctrine.yaml
index 8fe1dd4..80b4498 100644
--- a/doctrine/doctrine-bundle/2.4/config/packages/doctrine.yaml
+++ b/doctrine/doctrine-bundle/2.4/config/packages/doctrine.yaml
@@ -28,7 +28,7 @@ when@prod:
             auto_generate_proxy_classes: false
             query_cache_driver:
                 type: pool
-                pool: doctrine.system_cache_pool
+                pool: doctrine.query_cache_pool
             result_cache_driver:
                 type: pool
                 pool: doctrine.result_cache_pool
@@ -36,7 +36,7 @@ when@prod:
     framework:
         cache:
             pools:
+                doctrine.query_cache_pool:
+                    adapter: cache.app
                 doctrine.result_cache_pool:
                     adapter: cache.app
-                doctrine.system_cache_pool:
-                    adapter: cache.system
```

I could open a PR if you agree with these changes.

**Comment by alexislefebvre** [comment]
The documentation also use the pools and driver in reverse order: https://symfony.com/doc/5.4/reference/configuration/doctrine.html#caching-drivers

**Comment by kbond** [comment]
I believe the query cache is typically smaller so would benefit from the slight perf benefit of `cache.system`.

**Comment by alexislefebvre** [comment]
@kbond thanks for your answer, could you please explain why and how these 2 caches have different performances?

**Comment by alexislefebvre** [comment]
>     * `query_cache_driver` uses `doctrine.system_cache_pool`: this is surprising

This made sense when 2 caches used the same pool: https://github.com/symfony/recipes/blob/f54b694258dfcb356f6c59e2ce1a4c49f3cceae9/doctrine/doctrine-bundle/2.0/config/packages/prod/doctrine.yaml

Renaming `doctrine.system_cache_pool` to `doctrine.query_cache_pool` would probably confuse users and generate conflicts when updating the recipes.

So let's keep it as is.

Thanks all for your help in understanding this configuration.
