### ISSUE TITLE
[doctrine-bundle] v. 2.4 file does not exists `docker-compose.yml`

### ISSUE THREAD

**Issue by Chris53897** [symfony/recipes#1120]
I get the warning that the file does not exists `docker-composeyml`. (Missing .). Mac M1.
The file `docker-compose.yml` does exist in my project.
As it is correct in https://github.com/symfony/recipes/blob/b3395a2477b6d58089f92ef3a0d2e58226825a3a/doctrine/doctrine-bundle/2.4/manifest.json it is maybe a problem of the system itself?

`composer recipes:update doctrine/doctrine-bundle 
  Updating recipe for doctrine/doctrine-bundle...

                        
   Yes! Recipe updated! 
                        

  The recipe was updated but with one or more conflicts.
  Run git status to see them.
  After resolving, commit your changes like normal.

  NOTE:
  The file docker-composeyml was not updated because it doesn't exist in your app.

  Would you like to save the "diff" to a file so you can review it? (Y/n) Y

  Saved diff to doctrine.doctrine-bundle.updates-for-deleted-files.patch

  * [doctrine-bundle] Upgrade to Postgres 14 and MySQL 8 (PR https://github.com/symfony/recipes/pull/1115)
`

P.S. The post-install notice should be updated to postgres 14 as well.
https://github.com/symfony/recipes/blob/b3395a2477b6d58089f92ef3a0d2e58226825a3a/doctrine/doctrine-bundle/2.4/post-install.txt

Maybe this Line too. https://github.com/symfony/recipes/blob/main/doctrine/doctrine-bundle/2.4/config/packages/doctrine.yaml#L7

**Comment by maxhelias** [comment]
As you said, this is a warning and not an error. The `docker-compose.yml` file is not needed all the time.
And for the doctrine.yaml file, the line is commented and as indicated above it is better to configure in the variable DATABASE_URL : https://github.com/symfony/recipes/blob/main/doctrine/doctrine-bundle/2.4/config/packages/doctrine.yaml#L5-L6

**Comment by Chris53897** [comment]
But the file docker-compose.yml is changed for this recipe update.
https://github.com/symfony/recipes/pull/1115/files#diff-165a659908533726dd8891a603861852a2dbb90d0cb5cd90045f1723acfe3e18

**Comment by Chris53897** [comment]
Yes

**Comment by maxhelias** [comment]
So you should have a `docker-compose.yml` file at the root of your project. See more info : https://symfony.com/doc/current/setup/docker.html#flex-recipes-docker-configuration

**Comment by Chris53897** [comment]
Please see above `The file docker-compose.yml does exist in my project.`
I guess that symfony/flex has an error with detect the correct filename.
`docker-composeyml` vs `docker-compose.yml`

**Comment by mahono** [comment]
The problem still exists.

**Comment by mahono** [comment]
This must be a general issue. I also get it when upgrading the symfony/mailer recipe. It then says:

The file docker-composeoverrideyml was not updated because it doesn't exist in your app.

Dot missing before yml as well.

**Comment by weaverryan** [comment]
yea, that's super weird. It, indeed, looks like something with the recipe update system is losing the `.` in some cases... and only under some conditions. I believe the diff you posted is generated here - https://github.com/symfony/flex/blob/2.x/src/Update/RecipePatcher.php#L109 - so it's generated FROM git, so it's hard to imagine how it would generate a diff that's missing the `.` in the filenames... and this is so rarely reported, it makes me think that it works on most systems, but breaks on just a few.

**Comment by weaverryan** [comment]
Fixed at https://github.com/symfony/flex/pull/987

**Comment by Chris53897** [comment]
Thanks @weaverryan
