### ISSUE TITLE
Lock alias is not working

### ISSUE THREAD

**Issue by pierredup** [symfony/recipes#1150]
The `lock` alias already exists in the recipe (https://github.com/symfony/recipes/pull/1146#issuecomment-1321812674)
https://github.com/symfony/recipes/blob/7e2f8be50205ce92893bec7fa65479f370b6de9a/index.json#L149

But it's not working when trying to install the lock component.

<img width="278" alt="Screenshot 2022-11-21 at 13 05 17" src="https://user-images.githubusercontent.com/144858/203035597-3144a2bb-15b7-4512-a009-89dbebbd5085.png">

**Comment by pierredup** [comment]
This should be resolved in https://github.com/symfony/flex/pull/960

**Comment by fabpot** [comment]
Let's close it here then.
