### ISSUE TITLE
Issues when umask is disabled via disable_funtions

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/recipes#116]
To make things work out-of-the-box, some Flex recipes use `umask()`:

* https://github.com/symfony/recipes/blob/master/symfony/console/3.3/bin/console#L10
* https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/3.3/public/index.php#L19

As reported in https://github.com/symfony/symfony/issues/18672, this function can be disabled in some hosting services. Should we care about this? Should we add the `@` operator to those function calls?

**Comment by fabpot** [comment]
We should probably test for `umask` availability before calling them, I think that's all we need to do.

**Comment by fabpot** [comment]
I've just closed the upstream report. I'm closing this one as well as I'm not sure we should care about hosting providers which tweak PHP so drastically.
