### ISSUE TITLE
A "composer require" of a library should never lead to changes in the configuration of an application.

### ISSUE THREAD

**Issue by fck-ms** [symfony/recipes#1169]
This is only acceptable behavior for bundles and packs. As api-platform/core is a library (according to the composer.json file) there should be no recipes.

**Comment by fck-ms** [comment]
Created issue for api-platform/core, see https://github.com/api-platform/core/issues/5357 and https://github.com/symfony/recipes/pull/1168.

**Comment by derrabus** [comment]
> This is only acceptable behavior for bundles and packs

I don't know where this statement is coming from, but Flex is not designed around this principle.

If you browse the list of packages in this repository, you'll certainly find more examples. Not every library needs a bundle for being integrated into a Symfony application.
