### ISSUE TITLE
Class "PHPUnit\TextUI\Command" not found for phpunit/phpunit:10

### ISSUE THREAD

**Issue by valodya-street** [symfony/recipes#1173]
https://github.com/symfony/recipes/blob/b1176e36c42b0738c1475960202d7e074863ca3c/symfony/phpunit-bridge/5.3/bin/phpunit#L11

**Comment by weaverryan** [comment]
Yup, I'm guessing that file needs an update for phpunit 10

**Comment by stof** [comment]
The Symfony phpunit bridge does not support PHPUnit 10 yet. This is known and tracked at https://github.com/symfony/symfony/issues/49069

**Comment by nicolas-grekas** [comment]
Fixed by https://github.com/symfony/test-pack/pull/19 in practice.

**Comment by manuelcanga** [comment]
This can be mixed if you replace `PHPUnit\TextUI\Command::main()' to:

```php
(new \PHPUnit\TextUI\Application())->run($GLOBALS['argv']);
```

More details: https://dev.to/manuelcanga/fix-symfony-6x-tests-with-phpunit-10-18a1

**Comment by melroy89** [comment]
Yes so actually it's with `exit()`:

```php
exit((new \PHPUnit\TextUI\Application())->run($GLOBALS['argv']));
```

**Comment by derrabus** [comment]
See #1249

**Comment by melroy89** [comment]
Interesting my composer `phpunit/phpunit` recipe was up to date. And this code you showed me is not working with PHPUnit v10.. 

` PHPUnit\TextUI\Command` does not exists anymore in PHPUnit v10.

You will get:

```
$ ./bin/phpunit tests/Unit
PHP Fatal error:  Uncaught Error: Class "PHPUnit\TextUI\Command" not found in /blabla/balbalba/project/bin/phpunit:11
Stack trace:
#0 {main}
  thrown in /blab/blbla/project/bin/phpunit on line 11
  ```

**Comment by vinceAmstoutz** [comment]
> @derrabus Interesting my composer `phpunit/phpunit` recipe was up to date. And this code you showed me is not working with PHPUnit v10..
> 
> ` PHPUnit\TextUI\Command` does not exists anymore in PHPUnit v10.
> 
> You will get:
> 
> ```
> $ ./bin/phpunit tests/Unit
> PHP Fatal error:  Uncaught Error: Class "PHPUnit\TextUI\Command" not found in /blabla/balbalba/project/bin/phpunit:11
> Stack trace:
> #0 {main}
>   thrown in /blab/blbla/project/bin/phpunit on line 11
> ```
> 
> Hence the reason for the change I showed above.

It works for me, what is your Symfony version?

**Comment by melroy89** [comment]
> It works for me, what is your Symfony version?

Classic answer.

Again I'm using `phpunit/phpunit` package version **10.4.2**. Currently we are running Symfony version 6.3.8. If you use the latest PHPUnit version you can not have `TextUI\Command`, you still have this in the `bin/phpunit` command? If so, you are not running php 10.4.x. If not, then what do you have in your `bin/phpunit` script, and did a recipe update this?

**Comment by melroy89** [comment]
> And your `symfony/phpunit-bridge` recipe is up to date? For me it's works perfectly with Symfony 6.4, `phpunit/punit v.10.4.*` and the recipe updated!

I clean everything up I re-ran the phpunit-brdige recipe to ref `1f5830c331065b6e4c9d5fa2105e322d29fcd573` using the latest `phpunit.xml.dist` and phpunit script, now it seems to work again. Strange it didn't work in the past. Maybe it has to do something with this if check: `if (PHP_VERSION_ID >= 80000)`..

**Comment by derrabus** [comment]
I'm locking this conversation now because it's not about the original bug anymore. Please use our support channels as @wouterj already explained.
