### ISSUE TITLE
[DoctrineBundle] `collect-backtrace` enabled for all environments, not just dev

### ISSUE THREAD

**Issue by OskarStark** [symfony/recipes#1257]
> this enables for all environments, not just dev env (contrary to the title of the PR).
When running tests, you probably have the profiler enabled (to use it in assertions), but you are unlikely to care about the backtraces being collected in the details of each query. And those backtraces are increasing memory usage of the DBAL collector a lot.

_Originally posted by @stof in https://github.com/symfony/recipes/issues/1223#issuecomment-1816909863_

**Comment by stof** [comment]
See https://github.com/symfony/symfony/issues/52634#issuecomment-1816900168 for a case where this was reported as causing memory issues.
