### ISSUE TITLE
[Doctrine Bundle] Pin versions in Dockerfile

### ISSUE THREAD

**Issue by LaurentSanson** [symfony/recipes#1266]
Hi there,

I've encountered a small issue with the ORM bundle recipe and using the Hadolint on the CI (it all come from the [Kevin's template](https://github.com/dunglas/symfony-docker)).

**Issue :**
 Error: Dockerfile:51 DL3018 warning: Pin versions in apk add. Instead of `apk add <package>` use `apk add <package>=<version>`

**How to reproduce :** 

- Use the template
- Add ORM bundle
- Git push on main branch

I'm guessing we could probably add a version of the package in the recipe as suggested?

Thanks !

**Comment by maxhelias** [comment]
Hello,
This error should no longer occur with the latest version of recipes : https://github.com/symfony/recipes/blob/main/doctrine/doctrine-bundle/2.9/manifest.json#L19

**Comment by LaurentSanson** [comment]
Oh great !! Thanks for the quick feedback

**Comment by LaurentSanson** [comment]
@maxhelias I've just checked the recipes. The one you pointed at is the 2.9 and it's not the latest as there is a 2.10 => https://github.com/symfony/recipes/blob/main/doctrine/doctrine-bundle/2.10/manifest.json#L18

**Comment by maxhelias** [comment]
I missed 2.10.. which should have the same dockerfile section as 2.9...

**Comment by LaurentSanson** [comment]
No probs, I've created the [PR](https://github.com/symfony/recipes/pull/1269). Tell me if it needs more info :)
