### ISSUE TITLE
api recipe can't be installed due to minimum-stability 

### ISSUE THREAD

**Issue by mappedinn** [symfony/recipes#140]
Hi,

I would like to use `api-platform/api-platform` in my flex-enabled symfony application. To do so, I run the following commands:

```sh
# creation of the flex-enable symfony application
composer create-project symfony/skeleton:3.3.* sf-flex

# installation of the api recip
composer req api
```

Unfortunately, I am getting this error message:

**[InvalidArgumentException]                                                                                                                         
Could not find package api-platform/api-pack at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability** 
                                                                                                                                                         

**require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]**

To avoid that problem, I tried several solutions:

**Solution 1**
```sh
composer create-project symfony/skeleton:3.3.x-dev sf-flex
composer req api
```
**SAME ERROR**

**Solution 2**
```sh
composer create-project symfony/skeleton:3.3.x-dev sf-flex # with a newer version of symfony/skeleton
composer req --dev api
```
**SAME ERROR**

**Solution 3**

I tried to update the file `composer.lock` by changing that field as follows:

```json
    # "minimum-stability": "stable", # has been changed to to dev
    "minimum-stability": "dev",
```

**SAME ERROR**

So, any proposal??

Thanks,

**Comment by mappedinn** [comment]
Based on this [page](https://igor.io/2013/02/07/composer-stability-flags.html), I just changed `composer.json` by adding this line:

```json
"type": "project",
    "license": "proprietary",
    "minimum-stability": "dev",    // the added line
    "require": {
        "php": "^7.1.3",
// ...
```

And the API recipe is installed without problems...

**Comment by fabpot** [comment]
The problem is not related to Flex itself but to the fact that `api-platform/api-pack` has no tags yet. I've just created an issue on api-platform/api-pack to ask for a tag: api-platform/api-pack/issues/3

**Comment by stof** [comment]
this won't help much though: it requires a dev version of api-platform/core currently

**Comment by derrabus** [comment]
This command lets you install API platform without lowering your minimum stability globally:

```
composer require api-platform/api-pack:^2.1@dev api-platform/core:^2.1@dev
```

This could be a workaround until API platform releases stable versions for this recipe.

**Comment by mappedinn** [comment]
thank you @derrabus

**Comment by fabpot** [comment]
Tag has been created now.
