### ISSUE TITLE
Should controllers be private by default?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/recipes#141]
Controllers must be public when they have a `__construct()` method. Given that we allow to inject everything in the controller methods, most people will never use any constructor in any controller. 

So, should we make this change in the FrameworkBundle recipe?

```diff
# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../src/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    App\Controller\:
        resource: '../src/Controller'
-       public: true
        tags: ['controller.service_arguments']
```

**Comment by Pierstoval** [comment]
Not sure this would be a good idea from a DX perspective 🤔 People are not yet used to autowiring, and method arguments can be quite redundant when you have 3 methods in your controller that use the exact same tools.

Imagine a CRUD controller with the usual 5 actions: list, show, create, edit and delete. Most of these method will at least use services for Templating, Form factory, Routing and maybe form handlers. This sounds like a redundant to me to inject almost the same services in 5 methods and I'd rather have 4 or 5 services, maybe even lazy if you want to lighten the "list" and "show" actions.

Plus, having method actions with route parameters, request, user, and more services, make method actions very heavy, and the goal of the action is to be the lightest possible. Decoupling this with services in constructor makes things more readable to me.

Symfony 4 + Flex is changing so many things that I think we should keep some flexibility (no pun intended) for users not to complain everytime they want to do something that was very straightforward in Symfony 2 and 3.

**Comment by javiereguiluz** [comment]
@Pierstoval you are right. I was so focused on injecting things in controller methods, that I forgot that you can define a constructor for repeated arguments. Much better! Closing then.
