### ISSUE TITLE
when the recipe api will be available in a stable version?

### ISSUE THREAD

**Issue by mappedinn** [symfony/recipes#147]
Hi,

when the recipe api will be available in a stable version?

Actually, it can be installed only if `"minimum-stability"="dev"` as it can be seen in [the issue 140](https://github.com/symfony/recipes/issues/140). And this is causing me problem when traying to install the recipe `logger` and `cli`.

Thanks

**Comment by fabpot** [comment]
Not sure what "recipe api" means in this context. Anyway, I'm going to answer the other issue as it's not related to flex itself.

**Comment by stof** [comment]
The `api` alias references the api-platform project. And Flex support in api-platform is only available for 2.1+, which is not yet stable.

But the question about when api-platform 2.1 will be released should be asked to the api-platform maintainers. The recipes repo has no take on this date.
