### ISSUE TITLE
FrameworkBundle wrong Makefile when using cygwin

### ISSUE THREAD

**Issue by shude** [symfony/recipes#155]
How to reproduce:
Install PHP under windows environment
Install cygwin
Install FrameworkBundle and Cli

Then try to `make cache-clear`.
```
Could not open input file: [cygwin_path]/bin/console
```
In Makefile `$(shell which bin/console)` retreives a cygwin path instead of windows path.
To fix this, we need check $OS environment variable and if it equals Windows_NT then use
cygpath to retreive a path to console script:

`CONSOLE := $(shell cygpath -m "$(shell which bin/console)")`

**Comment by Pierstoval** [comment]
FrameworkBundle's Makefile cannot be updated to fit to Cygwin, you have to update it and keep it that way if it works for you. It has to be the most standard possible, and Cygwin is not "the most standard".

**Comment by shude** [comment]
@Pierstoval,  this is [your comment](https://github.com/symfony/flex/issues/62#issuecomment-298717309) about using cygwin in windows. When i think about shell in windows, first idea is use cygwin. How many people think the same way?

**Comment by Pierstoval** [comment]
I personally don't use Cygwin anymore (nor Mingw, nor any other shell emulator), stopped using them years ago, and if I need linux tools I switch to WSL, a more real bash environment that works like a charm without any dirty hack. This is 2017, Windows is bundled with a working Ubuntu shell that is not a basic emulated one, so it really works like linux would. Just some internal kernel-related stuff are not available.

And still, if `make serve` doesn't work in WSL, a simple `php bin/console server:run` won't cause any issue, and it's **more** native than using the makefile.

**Comment by shude** [comment]
I think you're right. Thank you for the discussion.
