### ISSUE TITLE
Rename var/logs to var/log

### ISSUE THREAD

**Issue by fabpot** [symfony/recipes#164]
as on *nix... Don't remember why I named it logs in the first place.

**Comment by Pierstoval** [comment]
Maybe because it's more understandable: "directory that contain logs".

Many projects are using either `log` or `logs`, it's more a matter of taste

**Comment by javiereguiluz** [comment]
We've always recommended to use `%kernel.logs_dir%` in config files, so I guess this won't cause any problem for our users (except for external apps (e.g. cron jobs) which contain the `var/logs/` string hardcoded).
