### ISSUE TITLE
Will env vars work on the Makefile?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/recipes#18]
Looking at this:

```makefile
@test -f bin/console && bin/console cache:clear --no-warmup || rm -rf var/cache/*
```

The `rm -rf var/cache/*` part is not very granular. Would env vars work in this file so we only delete the current environment cache? Something like this:

 ```makefile
@test -f bin/console && bin/console cache:clear --no-warmup || rm -rf var/cache/$(APP_ENV)
```

According to https://www.gnu.org/software/make/manual/html_node/Setting.html you can assign a default value to an env var:

```
APP_ENV ?= *
```

**Comment by Pierstoval** [comment]
It is possible to use the `.env` file by just adding this in the Makefile:

Makefile:
```makefile
include .env

test:
	@echo ${MY_ENV}
```

`.env` file:
```shell
# .env
MY_ENV="Hello"
```

Script:
```shell
$ make test
Hello
```

This way, any env var declared via the syntax you found on gnu.org will be overriden with the ones found in `.env`, even if you declare them **after** the `include` statement.

**Comment by fabpot** [comment]
Using `include .env` is not possible as the `.env` file should only be available in dev mode, not in prod, where "real" env vars are defined. So, this should be included conditionally (probably like is done in the web front controller), in which case, that would indeed be a good idea.

**Comment by Pierstoval** [comment]
It's still possible to include only if the env var is not defined:

```makefile
ifndef APP_ENV
	include .env
endif

test:
	@echo "APP_ENV:${APP_ENV}"
```

By default, it shows nothing. If the `.env` file does not exist, an error is thrown. Else, it includes it and variables are imported automatically in the makefile

**Comment by fabpot** [comment]
I've changed the Symfony Flex Composer plugin to write @Pierstoval snippet when creating the `Makefile` file the first time (symfony/flex@a482177).

Regarding the initial question by @javiereguiluz, the `rm -rf` part is really just a fallback, in which case, I prefer to remove everything. So closing this issue now.

**Comment by Pierstoval** [comment]
The flex repo is still not public, but we'll see when it'll be, I can't wait to see how it looks 😄
