### ISSUE TITLE
Different default debug value between CLI/web

### ISSUE THREAD

**Issue by ro0NL** [symfony/recipes#184]
https://github.com/symfony/recipes/blob/master/symfony/console/3.3/bin/console#L25 (`$_SERVER['APP_DEBUG'] ?? true`)
vs. 
https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/3.3/public/index.php#L15 (`$_SERVER['APP_DEBUG'] ?? false`)

Is that intended?

Also id suggest a default value of "1" or "0". This mixes string/boolean type.

**Comment by yceruto** [comment]
Related to https://github.com/symfony/recipes/pull/163?

**Comment by ro0NL** [comment]
Hm weird :) (sorry not really aware of changes in this repo :))

Personally i use same defaults for both now, and so same behavior for both. i.e. `$debug = '1' === ($_SERVER['APP_DEBUG'] ?? '1')` 

If intended, we can close this.

**Comment by fabpot** [comment]
That's intended. If the env var is not defined, we want a safe default, which is no debug.

**Comment by ro0NL** [comment]
Im not sure we should assume default debug in CLI is safer, then default debug in web :) but i think this is the reasoning behind it.

**Comment by fabpot** [comment]
My comment was more about having `false` as a default. As far as the difference between CLI and Web, it probably makes sense to have the same value for both.

**Comment by ro0NL** [comment]
`false !== '0'` enables debug ;-)
