### ISSUE TITLE
Remove dev/routing.yaml

### ISSUE THREAD

**Issue by ro0NL** [symfony/recipes#185]
https://github.com/symfony/recipes/blob/master/symfony/routing/3.3/config/packages/routing.yaml#L3

Should we make this `strict_requirements: '%kernel.debug'`?

**Comment by yceruto** [comment]
> 'true' is the preferred configuration in development mode, while 'false' or 'null' might be preferred in production:

https://github.com/symfony/recipes/blob/b22eb247d4f8f96665fc3e6b8ba5d279acad2d98/symfony/routing/3.3/config/packages/routing.yaml#L1-L3

 * set to true to throw an exception when a parameter does not match the requirements.
 * set to false to disable exceptions when a parameter does not match the requirements (and return null instead).
 * **set to null to disable parameter checks against requirements.**

I guess did you mean here?:
https://github.com/symfony/recipes/blob/b22eb247d4f8f96665fc3e6b8ba5d279acad2d98/symfony/routing/3.3/config/packages/dev/routing.yaml#L1-L3

**Comment by ro0NL** [comment]
You're right, this is true|false|null. Bummer; I knew this BTW :) https://github.com/symfony/symfony/issues/23532#issuecomment-315604284

Still in favor of true|false yes :) (where null behavior acts as false). Making kernel.debug a more sensible default. IMHO this is safe to trigger based on debug, rather then environment.

So this PR is too quick :) should we do something?

**Comment by stof** [comment]
Well, removing the behavior we have for `null` is a bad idea, as it is the one with the better performance (as checks are not performed at all).

But IMO, using the environment for this distinction is totally fine (different environments are about having different config)

**Comment by fabpot** [comment]
We already discussed that in another issue, and the current way is already optimized. So, closing this.
