### ISSUE TITLE
Recipe for "public/.htaccess" file

### ISSUE THREAD

**Issue by aik099** [symfony/recipes#190]
I can't find a recipe that would install default ".htaccess" file (see https://github.com/symfony/symfony-standard/blob/3.3/web/.htaccess) into "public" folder so that all mod-rewrite urls would still work.

Without it after fresh install I'm getting 404 on any route access (including routes generated by Web Profiler).

**Comment by fabpot** [comment]
Good idea. Can you work on a apache recipe?

**Comment by javiereguiluz** [comment]
Beware that this idea was proposed in the past (see #78) and rejected by the community.

**Comment by aik099** [comment]
@javiereguiluz, if I read #78 correctly, then it's about keeping `.htaccess` in folders others then `public` and that indeed is no longer an issue.

@fabpot , sure, why not. Please specify values for:

* recipe name
* recipe tags (if any)

I guess the recipe would:

1. contain https://github.com/symfony/symfony-standard/blob/3.3/web/.htaccess file with `app.php` replaced with `index.php`
2. copy (on install)/remove (on uninstall) that file into `public` file of the project

Is that correct?

**Comment by fabpot** [comment]
First, I think such a recipe should be part of `symfony/recipes-contrib` instead of this one (so no tag).
Then, we would need a "virtual" package like the one we have for encore (https://github.com/symfony/webpack-encore-pack/blob/master/composer.json). The name could `symfony/apache-pack`.

Having the file from the standard edition is probably the best idea (I've not been using Apache for years, so I cannot help on its contents). Copying/removing is done automatically by Flex (so nothing special here).

**Comment by Pierstoval** [comment]
Having an `.htaccess` file is not the best practice we can have. As we don't have any nginx pack for today, I'd rather disapprove recommending the use of an `.htaccess` file and instead propose the user to look for documentation instead on how to setup an Apache vhost with the correct rules.

The only reason to provide an `.htaccess` file is to help devs not remembering how to load a front controller. Symfony already has [web-server config docs](https://symfony.com/doc/current/setup/web_server_configuration.html) which are maintained, it's available when discovering Symfony in a few clicks ( `symfony.com` > `Documentation` > `1. Setup` > `Configuring a Web Server` tip link).

Symfony is bringing best practices on the table with Flex, with PHP7 requirements, etc., so I think it'd be a great idea to remove the `.htaccess` file and encourage devs to setup config in their vhosts (which is not a problem, updating vhost & reloading server is not much harder than updating `.htaccess`...).

**Comment by aik099** [comment]
@Pierstoval helps if you have single VirtualHost and have several projects on it, that are accessed like:

* http://my-dev-machine.com/project-one/public/
* http://my-dev-machine.com/project-two/public/
* ...

Much easier to add new project this way. And that also supports parallel project development using non-Symfony stuff, like WordPress and such.

Anyway recipe is optional, so nobody is forcing you to install it.

**Comment by aik099** [comment]
> https://github.com/symfony/recipes/issues/190#issuecomment-336156696

@fabpot , then please create such `symfony/apache-pack` repository.

**Comment by fabpot** [comment]
@aik099 Done. Pack is now created and version 1.0.0 is on Packagist.

**Comment by stof** [comment]
> Having an .htaccess file is not the best practice we can have.

and this is why the recipe will go in contrib

**Comment by fabpot** [comment]
Closing as there is now a recipe in contrib.

**Comment by aik099** [comment]
Thanks.
