### ISSUE TITLE
Attempt to install "form" recipe results in exception on cache warmup

### ISSUE THREAD

**Issue by aik099** [symfony/recipes#191]
The default configuration of `form` recipe has validation enabled and in that case during cache warmup I'm getting this error, when I haven't previously installed validation package:

```
...
Writing lock file
Generating autoload files
Executing script make cache-warmup [KO]
 [KO]
Script make cache-warmup returned with error code 2
!!  
!!  
!!                                                                      
!!  
!!  
!!    [Symfony\Component\DependencyInjection\Exception\LogicException]  
!!  
!!  
!!    The Validator component is required to use the Form component.    
!!  
!!  
!!                                                                      
!!  
!!  
!!  
!!  
!!  make: *** [cache-clear] Error 1
!!  
!!  

Installation failed, reverting ./composer.json to its original content.
```

**Comment by fabpot** [comment]
As said in the error, you must install the validator component as well.

**Comment by aik099** [comment]
If `symfony/form` component needs `symfony/validation` component to work properly, then maybe we should reflect that in `composer.json` file of `symfony/form` component?

**Comment by fabpot** [comment]
form can work without validation, but it is required when used via framework bundle.

**Comment by aik099** [comment]
Ah, didn't know that. Thanks for explaining. Then no changes are needed as you've initially told.

**Comment by fabpot** [comment]
Better experience on Symfony 3.4 now thanks to symfony/symfony#24303
