### ISSUE TITLE
Add the "cache" recipe

### ISSUE THREAD

**Issue by aik099** [symfony/recipes#194]
Right now, when installing `symfony/cache` package no sample config with sensible defaults is created and I need to go an enable caching manually.

**Comment by nicolas-grekas** [comment]
If you install FrameworkBundle, cache is installed as a required dependency and used automatically by default for most if not all system caches + an cache.app pool is provided by default.
What else would you expect?

**Comment by aik099** [comment]
Ah. It was I who added some cache configuration in my `app/config/config.yml` file. I thought these were default settings. Then indeed no config is needed. Thank you.
