### ISSUE TITLE
Chance to supress a bundle regestration

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony/recipes#196]
Hi,
is there a chance to supress a bundle registration of a dependency of my dependencies?
Can i explizit restrict the list of bundle which go into `bundles.php`through my reciepe?

Background:
My `symfony-cmf/seo-bundle` requires `sonata-project/seo-bundle`. Unfortunately they also require their `sonata-project/block-bundle`, which should be optional, which is registered instead. This bundle, which i don't wanna use requires me to set a default configuration. So i don't whant `\Sonata\BlockBundle\SonataBlockBundle` not to be registered.

**Comment by sstok** [comment]
Can you confirm that the `sonata-project/seo-bundle` works when the block-bundle is not registered? if so the Sonata sonata-project/seo-bundle needs to be updated to not require the block bundle (as Symfony 3.3+ does).

**Comment by fabpot** [comment]
I agree with @sstok that this is a big that should be fixed upstream. In the meantime, you can remove the registration from `bundles.php` and the generated configuration, which is always a possibility and fixes your "is there a chance to supress a bundle registration of a dependency of my dependencies?" question.
