### ISSUE TITLE
Deprecation Notice for easyadmin

### ISSUE THREAD

**Issue by pauli** [symfony/recipes#198]
While migrating a project to flex, I got the following deprecation notice for easyadmin.
User Deprecated: The JavierEguiluz\Bundle\EasyAdminBundle\EasyAdminBundle class is deprecated since version 1.16 and will be removed in 2.0. Use the EasyCorp\Bundle\EasyAdminBundle\EasyAdminBundle class instead.
Flex installed latest v1.17.1 but registered the old (with 1.17) deprecated bundle class. Fixing without flex is a no brainer but with flex the manifest.json should be changed.

**Comment by javiereguiluz** [comment]
You are right. This was already fixed in https://github.com/javiereguiluz/EasyAdminBundle/pull/1827 and it will be available in the next stable version of the bundle. Thanks!

**Comment by pauli** [comment]
@javiereguiluz just to be sure i was talking about this line [https://github.com/symfony/recipes/blob/2f672602bc4ffc1293a8f0ac9b367ded093176b8/javiereguiluz/easyadmin-bundle/1.16/manifest.json#L3](url)
Ist used because there is no newer 1.17 version of it

**Comment by javiereguiluz** [comment]
You are right again :)  I've created #199 to fix this problem. Thanks!
