### ISSUE TITLE
Symfony app workflow without CLI?

### ISSUE THREAD

**Issue by aik099** [symfony/recipes#211]
The Symfony Flex doesn't install much by default, but does it make sense not to install `cli` recipe? Without it you can't even reset caches in production and almost all apps want to get into production at some point.

**Comment by javiereguiluz** [comment]
In the Makefile we have this task to clear the cache even when you don't have `cli` installed:

```bash
cache-clear: ## Clears the cache
ifdef CONSOLE
	@bin/console cache:clear --no-warmup
else
	@rm -rf var/cache/*
endif
.PHONY: cache-clear
```

And about "resetting caches in production", I don't think we should care about that because it's a bad practice. Production caches are only removed/created after each redeploy.

**Comment by aik099** [comment]
Wasn't aware, that there is a polyfill for cases, when console isn't present. Then this isn't an issue at all. Thanks.
