### ISSUE TITLE
Recipe for "tests" directory

### ISSUE THREAD

**Issue by aik099** [symfony/recipes#212]
In the https://github.com/symfony/symfony-standard there were bundled `tests` directory and sample PHPUnit configuration. I wasn't able to find a recipe that would add them.

**Comment by Pierstoval** [comment]
There's already a default PHPUnit configuration in the [phpunit/phpunit](https://github.com/symfony/recipes/tree/master/phpunit/phpunit/4.7) recipe.

Creating the `tests/` directory is up to you 😄

**Comment by fabpot** [comment]
You get a default phpunit.xl.dist when installing `phpunit/phpunit` or `symfony/phpunit-bridge`. We could add the creation of the `tests/` directory as well in these two recipes. Would you mind submitting a pull request?

**Comment by aik099** [comment]
Sure. I'll put this on my list. By the way what about #190, where you should confirm desired course of action for a PR?

**Comment by fabpot** [comment]
see #280
