### ISSUE TITLE
App broken if doctrine/doctrine-bundle is installed without doctrine/orm

### ISSUE THREAD

**Issue by fbourigault** [symfony/recipes#218]
When you require the `doctrine/doctrine-bundle` package but not the `doctrine/orm` one you get the following exception:
```
[LogicException]
  To configure the ORM layer, you must first install the doctrine/orm package.
```

This is because the https://github.com/symfony/recipes/blob/master/doctrine/doctrine-bundle/1.6/config/packages/doctrine.yaml#L4-L14 file is configuring the ORM which may be not installed.

I know this is not so easy as those configuration can't be moved in the `doctrine/orm` package as installing this one without the bundle would also break the application.

**Comment by aik099** [comment]
You can install `orm-pack` for now.

**Comment by fabpot** [comment]
Unfortunately, nothing we can do IMHO. We could remove the default `orm` configuration, but that's not what people would want most of the time. So, the best option is to be sure to document using the `orm-pack` instead of installing the bundle only.

**Comment by dimkir** [comment]
I wonder, if the documentation on DBAL usage https://symfony.com/doc/current/doctrine/dbal.html   which recommends installing `doctrine/doctrine-bundle` needs to be changed to recommend installing of the `orm-pack` ?

**Comment by erikbaan** [comment]
this is still an issue with the documentation.

**Comment by javiereguiluz** [comment]
@erikbaan see https://github.com/symfony/symfony-docs/pull/10127

**Comment by ryancastle** [comment]
Removing the `doctrine.orm` block in `config/packages/doctrine.yaml` resolves this, if you aren't wanting to install the ORM.
