### ISSUE TITLE
Executing script make cache:clear [KO]

### ISSUE THREAD

**Issue by marcossegovia** [symfony/recipes#231]
This happens when running `composer install`
Composer json is like
```
...
    "scripts": {
        "auto-scripts": {
            "make cache-warmup": "script",
            "assets:install --symlink --relative %PUBLIC_DIR%": "symfony-cmd",
            "cache:clear": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
...
```
It is the same response as if I only run `bin/console cache:clear`, by using `cache:clear --no-warmup`works well.

But what I do not really get it is that even though I modify the composer.json above, like:

```
    "scripts": {
        "auto-scripts": {
            "make cache-warmup": "script",
            "assets:install --symlink --relative %PUBLIC_DIR%": "symfony-cmd",
            "make cache-clear": "script"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
```
Despite having modified the `composer.json` (As there is an entry in the Makefile) to perform the cache clear without warmup, after running `composer install`, the composer json still gets automatically modified like:

```
    "scripts": {
        "auto-scripts": {
            "make cache-warmup": "script",
            "assets:install --symlink --relative %PUBLIC_DIR%": "symfony-cmd",
            "make cache:clear": "script",
            "cache:clear": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    }, 
```

Does this has to do with the recipe on https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/3.3/manifest.json ?

**Comment by fabpot** [comment]
You need to upgrade to the latest version of `symfony/flex`, that should fix the problem where a recipe is applied more than once. That will only fix the issue for the next time as Flex must first create a lock file. You should also remove the make entries as using a Makefile is not part of the recipes anymore.
