### ISSUE TITLE
DotEnv used even if component is not installed

### ISSUE THREAD

**Issue by garak** [symfony/recipes#235]
Framework-bundle and console recipes are using DotEnv, without checking if DotEnv component is installed.
So, after installing them, you get `bin/console` and `public/index.php` with reference to undefined Dotenv class.
I guess that such parts should be avoided when DotEnv component is not installed, and eventually added when DotEnv component is required
A possible alternate solution is that recipes require DotEnv component (IMHO not the best solution, since it's legitimate to not use DotEnv at all)

**Comment by fabpot** [comment]
If you are not using Dotenv, it means that you have defined the env vars in which case you won't have any errors.

**Comment by garak** [comment]
Ah, of course, no errors here.
But every time I run a static analysis I'm getting warnings about undefined class.
I see that this is a minor issue. Hope to see handled it anyway, just for the sake of integrity.

**Comment by fabpot** [comment]
What do you mean by "for the sake of integrity"? I won't make changes to please static analyzers :)

**Comment by xabbuh** [comment]
I could imagine one edge case here that would not be handled nicely: Neither having configured any env vars (intended or not intended) nor an installed Dotenv component. PHP will complain with a class it couldn't found. We could improve the experience here by throwing a meaningful exception. Though I am not sure if it's worth it.

**Comment by ro0NL** [comment]
Perhaps related, but the UX regarding DotEnv is not correct IMHO.

```
$ composer req symfony/skeleton:dev-master

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 21 installs, 0 updates, 0 removals
  - Installing symfony/flex (dev-master f3ac6de): Cloning f3ac6de242
  - Installing symfony/yaml (v4.0.0-BETA3): Loading from cache
  - Installing symfony/routing (v4.0.0-BETA3): Loading from cache
  - Installing symfony/polyfill-mbstring (dev-master 2ec8b39): Cloning 2ec8b39c38
  - Installing symfony/http-foundation (v4.0.0-BETA3): Loading from cache
  - Installing symfony/event-dispatcher (v4.0.0-BETA3): Loading from cache
  - Installing psr/log (dev-master 4ebe3a8): Cloning 4ebe3a8bf7
  - Installing symfony/debug (v4.0.0-BETA3): Loading from cache
  - Installing symfony/http-kernel (v4.0.0-BETA3): Loading from cache
  - Installing symfony/finder (v4.0.0-BETA3): Loading from cache
  - Installing symfony/filesystem (v4.0.0-BETA3): Loading from cache
  - Installing psr/container (dev-master 2cc4a01): Cloning 2cc4a01788
  - Installing symfony/dependency-injection (v4.0.0-BETA3): Loading from cache
  - Installing symfony/config (v4.0.0-BETA3): Loading from cache
  - Installing psr/simple-cache (dev-master 408d5ea): Cloning 408d5eafb8
  - Installing psr/cache (dev-master 78c5a01): Cloning 78c5a01ddb
  - Installing symfony/cache (v4.0.0-BETA3): Loading from cache
  - Installing symfony/framework-bundle (v4.0.0-BETA3): Loading from cache
  - Installing symfony/console (v4.0.0-BETA3): Loading from cache
  - Installing symfony/skeleton (dev-master 8725c24): Cloning 8725c24707
Writing lock file
Generating autoload files
Symfony operations: 4 recipes (db6148b5ea2a27b221184a968d83bf6a)
  - Configuring symfony/flex (1.0): From github.com/symfony/recipes:master
  - Configuring symfony/routing (3.3): From github.com/symfony/recipes:master
  - Configuring symfony/framework-bundle (3.3): From github.com/symfony/recipes:master
  - Configuring symfony/console (3.3): From github.com/symfony/recipes:master
```

Side note; i expected i needed to manually install frameworkbundle actually :thinking: .

```
$ bin/console

PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Dotenv\Dotenv' not found in /var/www/html/test/bin/console:19
Stack trace:
#0 {main}
  thrown in /var/www/html/test/bin/console on line 19
```

**Comment by ro0NL** [comment]
@xabbuh you actually mentioned this :sweat: can we do something about it?

**Comment by xabbuh** [comment]
Well, the clean exception message would only help here in that you would know what package you'd need to install. But the script execution would still fail nonetheless.

**Comment by fabpot** [comment]
Using `composer req symfony/skeleton:dev-master` is not a supported use case.

**Comment by ro0NL** [comment]
@fabpot you're right.. no issues with `create-project` :+1:

**Comment by xabbuh** [comment]
see symfony/recipes#247
