### ISSUE TITLE
[Question] How can I tests new features in flex, that need modified recipies

### ISSUE THREAD

**Issue by kolibri** [symfony/recipes#246]
I ran into following problem: I wanted to add a feature to flex, that needs a new "feature" inside recipies (in detail: replace some variables inside copied files).

So, I needed custom recipies to test my stuff. This seems quite hard with the hard coupling with the symfony.sh endpoint and the two recipe repositories. Cloning/mocking symfony.sh seems a overkill, and I found no solution for replacing a recipe/recipe-repository like it is possible with composer packages and the `repositories` keyword.

What I hacked: Created a pull request inside the recipe repository, described it with "please, do not merge and delete", and used the endpoint replacement URL, that is created by the symfony bot.
But always with "there should be a better way to do that" in my mind.

So, is there a better way to do that?

**Comment by Pierstoval** [comment]
Isn't there a way to mock the connection between Flex and the repositories with a Stub?

**Comment by fabpot** [comment]
@kolibri has now everything he needs to test correctly :)
