### ISSUE TITLE
DATABASE_URL vs DB_* parameters

### ISSUE THREAD

**Issue by goetas** [symfony/recipes#266]
Is there a place where I can find a discussion where has been decided to use `DATABASE_URL` instead of `DB_*` parameters?

Commit: https://github.com/symfony/recipes/commit/2a7a22ac69e666ce8729e4b9bb02ed7670563054 by @fabpot 

Can't see advantages in it.

Here are some issues caused by it: https://github.com/symfony/symfony/issues/25010 https://github.com/symfony/flex/pull/200 symfony/recipes#233, #180, and #182 symfony/recipes#234 https://github.com/symfony/flex/issues/129 https://github.com/symfony/symfony/issues/23527 (and probably many others) almost all of them are already solved, but it seemed a weird move.

**Comment by javiereguiluz** [comment]
It's part of the Symfony goal of using more industry standard practices. Specifically, env vars and DSN-based config strings.

The change in the Database recipe was done in this commit: https://github.com/symfony/recipes/commit/2a7a22ac69e666ce8729e4b9bb02ed7670563054#diff-b0636e8ae717e7f34d06e12e6d5ef542

**Comment by goetas** [comment]
`DB_*` parameters were environment variables vars too. The issues and struggles by aggregating more or less 10 parameters into a single url-encoded one should have been considered too.

Documenting them is also an issue, when they were separated was much easier to add comments on them one-by-one.

Anyway, thanks for the answer, probably will have to live with it.

**Comment by javiereguiluz** [comment]
You could give it a try and if you don't like it ... you can go back to using separate parameters because they still should work.

**Comment by goetas** [comment]
yeah, I noticed it and will do probably a mix them (most probably for the `serverVersion` var). 

I'm more worried if I will not like it, but the other people will use it just because they did not see alternatives from the past :)

**Comment by goetas** [comment]
> I'm more worried if I will not like it, but the other people will use it just because they did not see alternatives from the past :)

My fears have been proved right at the SymfonyCon  this week :smile: 

https://www.garfieldtech.com/presentations/slides-cloud-friendly/sfconcluj2017/#/6/6

here you can see that:

1) on the comment 
```
// Hack the Doctrine URL to be syntactically valid in a build hook, even
// though it shouldn't be used.
```

Why define it if is not used?  (this is partially related to https://github.com/symfony/symfony/issues/25010)

2) `charset` and `serverVersion=10.2` are always there

3) `$endpoint['username'], $endpoint['password'], $endpoint['host'], $endpoint['port']`
were already available as separate parameters, why aggregating them in an "url", and later doctrine will have to re-decompose them again as separate parameters.

4) if the password contains `:` the code shown will not work, `urlencode` will be necessary.
