### ISSUE TITLE
Reconsider the last change about post-install

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/recipes#27]
In 77e841b4c0e057e29e8ab02013e8932b87f73f4b the way post-install output is defined changed. Instead of `post-install-output` inside the manifest.json, you now create a `post-install.txt` file.

I think this is wrong for these reasons:

1) It's true that the framework-bundle recipe looks ugly ... but that's the absolute edge case of this feature. You would usually display nothing or 1-2 simple lines.

2) If you make easy to display output ... people will spam the output. We want the opposite; that's why we took some time to hide as much useless Composer output as possible. I fear people will start displaying messages like: "Thanks for using the bundle Acme. Visit our website blah blah" and of course include a lot of useless emojis.

3) The non-edge case of this feature is to display just 1 or 2 short lines. That's where the previous way (`post-install-output` in manifest.json) is better than the new proposal (creating a micro-file called `post-install.txt`)

4) Managing 1 file with 50 lines is infinitely easier than managing 10 files with 5 lines each. Some developers don't think so and they are afraid of "long files" (anything longer than 10 lines), but that's a fallacy.

**Comment by iltar** [comment]
Maybe it would be possible to provide a template? This way you could add several options you can fill in:
 * homepage url
 * documentation url
 * optional contact methods:
   * IRC server + channel
   * Slack
   * email
   * etc.

This way you can validate the input while keeping a nice generic template available. Flex can be opinionated so I don't really see a problem in "enforcing" a specific format.

**Comment by sstok** [comment]
@iltar That would still clutter the post-install, `composer show` already allows to show the information from a package. No need to duplicate this imo 🤔 only when manual action/configuration is required (Doctrine ORM config-url for example).

**Comment by iltar** [comment]
When I'm installing a bundle, it would be nice to immediately have some meta information like a link to the documentation. it's always something interactive, via the CLI, never automated. Not sure if it's possible to install multiple bundles at the same time, but I would limit this to 1 for myself (for clarity) if it shows helpful information when the installation is done.

**Comment by sstok** [comment]
Then it should only be displayed when a single recipe is installed, is it even possible to install multiple at the same time?

**Comment by Pierstoval** [comment]
@iltar the link you need when installing a bundle is the link to the repository, which should store its documentation, or at least provide a link to the docs, so simply retrieving this from the composer package itself can be done without additionnal stuff in the recipes

**Comment by HeahDude** [comment]
@javiereguiluz Fabien is right, if recipes are reviewed and validated by the community, I can't find any good reason to revert this new way.

About @iltar's suggestion it sounds more like a Composer feature to me, some kind of (existing) command to read extra info about packages, but this should not be Flex's responsibility IMHO, which is only about hooking into Composer to configure things, and if needed add a small output to say it went well or advise a missing step (i.e running a command to start a web server).

**Comment by javiereguiluz** [comment]
Let's close this proposal as "won't fix". If this becomes a problem in the future we can always change things later. Thanks!
