### ISSUE TITLE
recipe fails if .env.dist is not present

### ISSUE THREAD

**Issue by garak** [symfony/recipes#270]
Not sure if related to #247 
My use case: I'm not using DotEnv, so there's no `.env.dist` file (I'm using real environment variables instead).
Recipes are failing on `"copy-from-recipe"` step, with the error: 
>copy(/project/.env.dist): failed to open stream: No such file or directory

I think that Flex should be flexible enough to support the absence of `.env.dist` file

**Comment by Pierstoval** [comment]
As you don't have `.env.dist`, where do you define the list of env vars that should be configured in your application?

**Comment by garak** [comment]
As I stated before, my env vars are actual environment variables, e.g. I can see them running `env` in a terminal

**Comment by fabpot** [comment]
@garak I think this is an edge case, but easy to support. Can you submit a PR on symfony/flex to check of the file exists before copying it?

**Comment by Pierstoval** [comment]
> As I stated before, my env vars are actual environment variables, e.g. I can see them running env in a terminal

I'm more talking about **where's the list of the needed variables**. It seems logic that your environment has them, but for anyone else working on the project, he/she will need a proper documentation about these variables, therefore an `.env.dist` file is the best place to go

**Comment by garak** [comment]
It's not just about other devs, even other environments are using vars (e.g. CI and production server). Anyway, my project is using docker and so env vars are stored inside `docker-compose.yaml` file (and, of course, they are the same for every dev is working on the project)
