### ISSUE TITLE
ExpressionLanguage not found 

### ISSUE THREAD

**Issue by erlangp** [symfony/recipes#291]
first i run command:
`composer req symfony/console symfony/flex symfony/framework-bundle symfony/yaml symfony/dotenv`

then:
`composer req validation profiler serializer orm http cli router debug security annots maker server logger template sec-checker req-checker phpunit mailer`

then:
`bin/console server:run`

i open browser and i get error code `500`

inside `dev.log` file:
`[2017-11-30 22:10:33] php.CRITICAL: Fatal Error: Class 'Symfony\Component\ExpressionLanguage\ExpressionLanguage' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Class 'Symfony\\Component\\ExpressionLanguage\\ExpressionLanguage' not found at C:\\Users\\SONY\\Desktop\\vendor\\symfony\\security\\Core\\Authorization\\ExpressionLanguage.php:24)"} []`

**Comment by Nyholm** [comment]
Thank you for this issue. 
Can you help me to reproduce this error? 

If I start with the following commands, what to do next?

```
composer create-project "symfony/skeleton:^4.0" sf
cd sf
```

**Comment by xabbuh** [comment]
I think this issue is the same as sensiolabs/SensioFrameworkExtraBundle#532.

So I am closing here for now until we come to the conclusion that this is indeed a different issue.

**Comment by erlangp** [comment]
@Nyholm 

i tried:
`composer create-project "symfony/skeleton:^4.0" sf`
`cd sf`

then:
`composer req validation profiler serializer orm http cli router debug security annots maker server logger template sec-checker req-checker phpunit mailer`

i got anther error:
...
    - Configuring symfony/swiftmailer-bundle (2.5): From github.com/symfony/recipes:master
    ocramius/package-versions:  Generating version class...
    ocramius/package-versions: ...done generating version class
    Executing script cache:clear [OK]
    Executing script assets:install --symlink --relative public [OK]
    Executing script security-checker security:check [KO]
     [KO]
    Script security-checker security:check returned with error code 255
    !!
    !!  Fatal error: Default value for parameters with a class type hint can only be NULL in X:\sf\vendor\symfony\console\Application.php on line 81
    !!  PHP Fatal error:  Default value for parameters with a class type hint can only be NULL in X:\sf\vendor\symfony\console\Application.php on line 81
    !!

    Installation failed, reverting ./composer.json to its original content.

**Comment by erlangp** [comment]
^ do i need to open other issue for this error?

**Comment by erlangp** [comment]
if i run command manually:
`bin/console security: check`
i got success.. no error..
