### ISSUE TITLE
[FrameworkBundle]: .env entries are partially missing

### ISSUE THREAD

**Issue by weaverryan** [symfony/recipes#298]
After starting a new Flex project, my `.env` file looks like this:

```
###> symfony/framework-bundle ###
APP_ENV=dev
APP_SECRET=fe508ae77083f5c4913279bf3df2306d
# 127.0.0.1,127.0.0.2
# localhost,example.com
###< symfony/framework-bundle ###
```

See the IP address and host names? Those are actually supposed to look like this: https://github.com/symfony/recipes/blob/921ee9045acc2240ad7aab10e490c41c44d0fbf4/symfony/framework-bundle/3.3/manifest.json#L18

But for some reason, the `#` at the beginning completely removes the environment variable name. I have no idea if this is a new issue or not... or the right way to fix it!

**Comment by fabpot** [comment]
PR here: symfony/flex#235
