### ISSUE TITLE
[Proposal] Recipe development

### ISSUE THREAD

**Issue by covex-nn** [symfony/recipes#299]
I suggest to store `composer.json` file in recipe’s directory. This file could help to launch flex-application to develop and test recipe before pushing it to GitHub and creating PR; and to speed up recipe development.

To show how it could be, I tried to create a recipe for `friendsofsymfony/user-bundle`. See https://github.com/symfony/recipes/pull/300. Eventualy, of course, I could not create recipe acceptable and functioning out-of-the-box, but at least it is clear what to do next.

To create a recipe, i modified `composer.json` from `symfony/skeleton`. First i moved all packages from `require` to `require-dev` section; than added `friendsofsymfony/user-bundle` to `require` section. If after each `composer update` or `bin/console cache:clear` there was a error message occured, i tried to fix it with configuration or with additional packages in `require` section.

Final `require` section (in real situation there must be only one requirement – recipe’s package):

```json
{
    "require": {
        "php": "^7.0.8",
        "doctrine/doctrine-bundle": "^1.8",
        "doctrine/orm": "^2.5",
        "friendsofsymfony/user-bundle": "^2.0",
        "symfony/doctrine-bridge": "^3.4",
        "symfony/validator": "^3.4",
        "symfony/swiftmailer-bundle": "^3.1",
        "symfony/templating": "^3.4"
    }
}
```

Final `require-dev` section:

```json
{
    "require-dev": {
        "symfony/console": "^3.4",
        "symfony/dotenv": "^3.4",
        "symfony/flex": "^1.0",
        "symfony/framework-bundle": "^3.4",
        "symfony/lts": "^3",
        "symfony/profiler-pack": "^1.0",
        "symfony/yaml": "^3.4"
    }
}
```

Further I set up a database. I’ve put `DATABASE_URL=sqlite:///%kernel.project_dir%/var/data.db` to `.env` file and run `bin\console doctrine:schema:create` to create all tables for a bundle.

At last I launched web-server via `php -S 127.0.0.1:8000 -t public` and registered my user on http://localhost:8000/register/

Before i pushed my changes to github I’ve gitignored everything except recipe’s files.

```
*
!.gitignore
!composer.json
!config/
config/*
!config/packages/
config/packages/*
!config/packages/fos_user.yaml
!config/routes/
config/routes/*
!config/routes/fos_user.yaml
!manifest.json
!src/
src/*
!src/Entity/
!src/Repository/
```

Now my recipe consists of 7 files an it can be modified and tested by anybody else easily.

What do you think?

**Comment by Pierstoval** [comment]
I'm not sure this is the right way to create or test a recipe. Just submit a PR and use the `SYMFONY_ENDPOINT` in order to create a project and you're set to test your recipe 😕

**Comment by covex-nn** [comment]
I have read about `SYMFONY_ENDPOINT` on [Symfony 4: Contributing Recipes](http://fabien.potencier.org/symfony4-contributing-recipes.html). But my host OS is Windows and i do not know how to use env variables easily =( `SYMFONY_ENDPOINT=https://symfony.sh/r/contrib/42 composer req foo/bar` won't work.

And a would never start to work in "`SYMFONY_ENDPOINT`-way" on fosub recipe, or on some other complex bundle's recipe. Because it's very difficult to start to work on it if this bandle is not your own. And using endpoint seems like unnecessary step in the very beginning

**Comment by Pierstoval** [comment]
It's as easy as reading [doc](https://superuser.com/questions/79612/setting-and-getting-windows-environment-variables-from-the-command-prompt) to know how to use env vars on windows.

And even if the bundle is not your own, installing a package and using Flex is possible for anyone...

**Comment by covex-nn** [comment]
@Pierstoval i know how to set variables =) I tried to say, that `VAR=value command` will not work on windows.

And i say `it is not convenient to me`, and you say - `it is possible to everyone`, so there is no dispute here. Yes, it is possible, but not convenient.

With my suggestion to create a recipe i must take following steps:

1. create `composer.json`
2. run `composer install`
3. create recipe and test it in a same place
4. push recipe to github (or not to push, if i failed)

And with `SYMFONY_ENDPOINT`:

1. create recipe
2. create new project somewhere else
3. push recipe to github
4. run `composer req foo/bar`
5. if there is something wrong, i run `composer remove foo/bar`, update recipe files, goto 3 (and there could be a lot of 'steps 3-4-5')

With my suggestion i could even add `phpunit.yml.dist` file to repository to test recipe configuration, with `SYMFONY_ENDPOINT` - i can not.

**Comment by Pierstoval** [comment]
I think it's not the best option to have a `composer.json` file in the recipe. This file must be in the package itself, not the recipe, else we'll have duplicates, and not everyone wants to use a recipe for a specific package, and the composer.json file is mandatory in the package.

It kinda echoes with #301

**Comment by covex-nn** [comment]
> This file must be in the package itself, not the recipe, else we'll have duplicates

No no! I am talking about a composer.json of recipe itself, not package! This `composer.json` will only help *to develop a recipe*, it is not a duplicate! Also we could create `phpunit.xml.dist`, to test recipe configuration, not a package. So, my suggestion is not about decentralization.

Btw, i've found an example: https://github.com/weaverryan/fos_user_flex_test - there @weaverryan created flex-application, to develop [recipe for fosub](https://github.com/weaverryan/fos_user_flex_test/blob/master/config/packages/fos_user.yaml). He does not use `SYMFONY_ENDPOINT` =) The only difference is that files are not gitignored and composer.json will not be shared for community.

**Comment by Pierstoval** [comment]
Yeah but this project doesn't call Flex when editing the recipe. It's just a plain Symfony project. And I can bet than when FOSUserBundle will be ready after @weaverryan's work, he will just copy the code he has in the config and paste it in a configuration.

I'm not sure Symfony team should provide such "big" feature: for **every** PR, the server should create an entirely working application to test the recipe? I'm not sure it's ok. Too many issues, edge cases, like, what if you need to update app config? What if you need to add another package to this "recipe test" environment to avoid issues, collisions or make sure compatibility is guaranteed? All of this rely on custom package logic and cannot be standardized in symfony.sh, therefore I'm not sure it's possible in any way to introduce such new feature to "test" recipes like this.

If you want to test a recipe, @weaverryan's way of doing it is the best way:
* Create a project
* Require your bundle
* Add the config you'd like to add in the future recipe
* Test it manually, write phpunit tests if you like
* When everything is ok, copy package's configuration, create a new directory in the recipes repo, paste the config in files, create your `manifest.json` and that's it.

I know it can seem cumbersome to have all these steps to make a recipe, but actually, standardizing all the things might be too complicated for the team to handle this in a "DX-friendly" way 😕
