### ISSUE TITLE
Recipes decentralized in the packages repositories

### ISSUE THREAD

**Issue by scuben** [symfony/recipes#301]
Not being an issue but more of a general question. I think you already thought of this while creating flex. In my opinion it would make sense not to have a dedicated recipe repository (or two with the contrib). Like we all have our composer.json file in the repository (and many more files related to many other services): Why not also have the recipe in the packages repository? I imagine it would not be a problem for flex to get the recipe from there due to it's downloading the packages anyways.

So... Did you already thought of this? What is the reason you went for dedicated repositories for the recipes?

**Comment by xabbuh** [comment]
see symfony/flex#206 :)
