### ISSUE TITLE
Ignore public/build when using webpack encore ?

### ISSUE THREAD

**Issue by mykiwi** [symfony/recipes#302]
Hi,

Is there a reason why the path `public/build` is not ignored when playing with symfony/webpack-encore ?

https://symfony.com/doc/current/frontend/encore/faq.html#what-files-should-i-commit-to-git-and-which-should-i-ignore

So, should we [ignore it](https://github.com/symfony/recipes/blob/master/symfony/webpack-encore-pack/1.0/manifest.json#L8) or add an other comment in the [webpack config](https://github.com/symfony/recipes/blob/master/symfony/webpack-encore-pack/1.0/webpack.config.js#L4)

**Comment by weaverryan** [comment]
you're right! We should ignore it! See #311

**Comment by MSefer** [comment]
Why we ignored build folder? Do not we need this folder in production? There is output files in this folder? How we use?

**Comment by OskarStark** [comment]
This should be part of a CI/CD step. The final build files shouldn’t be part of your repository.

**Comment by wardwj** [comment]
I am unsure of this also, the documentation states to `.gitignore` the `/public/build/` however this is needed on the production site?? Can someone put this in to context ?

**Comment by stof** [comment]
the .gitignore file configures what goes into the VCS repository, not what goes in the production server (the production server needs the `vendor` too, and it is also ignored from the git repo)
