### ISSUE TITLE
routing.yaml seems like a misleading name to me

### ISSUE THREAD

**Issue by vbourdeix** [symfony/recipes#303]
Having worked with symfony for many years, when I see a file called routing.yaml, my brain is used to tell me "you should find routes configuration in this file".

So when I see the router configuration in config/packages/routing.yaml, I find it misleading as it doesn't contains routes configuration but router configuration. Even if the file containing the routes has been renamed routes.yaml (which is a good thing), and then doesn't have the same name, would it not be better to call the router configuration file **router.yaml instead of routing.yaml** ?

It may feel like I'm quibbling, but I wanted to share my opinion about it.

**Comment by Pierstoval** [comment]
You're right about the fact that it contains _router_ configuration. But it was decided that config filenames were supposed to use the same name as the component they provide config for, and the component is named Routing, not Router

**Comment by vbourdeix** [comment]
Thanks for the explanation, I think it makes sense then. Keeping that in mind and the fact that routes may only appear in config/routes/* or routes.yml, I won't get mislead hopefully.
