### ISSUE TITLE
Run recipes force

### ISSUE THREAD

**Issue by proArtex** [symfony/recipes#304]
An existing project do not updates symfony.lock on composer install/update commands (updated from 3.3 to 3.4) as it do not configures recipes. The only way I made it is: composer remove target & composer install target. But even this method failed if any other dependency had target dependency in "require" section.
So, is there any way to force run recipe?

**Comment by Pierstoval** [comment]
If you want to re-run a recipe, you can remove the `vendor` directory and `symfony.lock` file (or just the recipes you want to reset in the `symfony.lock` file) and run `composer install` again.

**Comment by proArtex** [comment]
The point is symfony.lock contains empty array and composer install doesn't make sense. Removing of vendor/symfony/framework-bundle folder helped me. Thanks!

**Comment by fabpot** [comment]
To answer the initial question, there is no way to force a recipe to execute. Doing the @Pierstoval's way is fine though.
