### ISSUE TITLE
[RFC] Allow a recipe to be merged with other versions

### ISSUE THREAD

**Issue by Pierstoval** [symfony/recipes#317]
For issues like #316, the recipe needs a single file to be updated and the rest is quite similar.

Maybe we could think about a way to "merge" a recipe with the same recipe for another version? This could avoid having duplicate recipes with too few changes.

I'm not sure of any technical way to do it, because there might be several different cases, like merging a list of files, merging manifest rules...

WDYT?

**Comment by Nyholm** [comment]
A recipe is something you use when you install the dependency. You copy some default config down from the internet and then let the user modify it. In my opinion, it would lead to many weird side effects if you changed existing configuration on `composer update`. Even a command like `composer update-recipes` would not really be preferred. 

However, if this was not a "recipe repository" but a "configuration repository", your suggestion would make more sense.

**Comment by Pierstoval** [comment]
I think I haven't expressed myself correctly, I'm not talking about a composer command, but a way to avoid copy/pasting recipes when releasing a new version of a package.

It's just to merge recipes on symfony.sh.

Example:

A package defines a manifest that copies files, sets environment vars, a bundle, and scripts.
But let's imagine this package releases a new major version that optimizes some configuration options (let's say, the routing format, for the case of #316 ), and only one file in the recipe needs to be updated.

In order to avoid duplicating the recipe and changing a single file, we could simply add a new manifest for this new version, and have a rule in it that says something like _"Take this config from the previous version"_, and execute current version rules after that.

**Comment by Nyholm** [comment]
Ah, okey. I understand. That is a nice idea. 

How would the implementation look like? Should a bit complicated to try to figure out how many versions back we should go looking for config files. Also, how about readability? Right now if I want version 3.1 of package `foo` I can look at the recipe repo and find that version and know exactly what I would get.

**Comment by Pierstoval** [comment]
I'd like to have more opinions about the idea, but I'm wondering should we be able to import **only specific rules** or **all rules**?

I'm personally in the second option and override afterwards, therefore the implementation might look like this:

By importing manually all rules we need, and then, all we add will be merged:
```json
{
    "import_rules": {
        "3.1": [
            "copy-from-recipe"
        ],
        "4.0": [
            "bundles"
        ]
    },
    "copy-from-recipes": {
        "new_dir/": "%PROJECT_DIR%/new_dir/"
    }
}
```

Or just specify the recipe versions, everything will be retrieved in the specified order, all we add manually will be overriden:
```json
{
    "from": [
        "3.1", "3.2"
    ],
    "copy-from-recipes": {
        "new_dir/": "%PROJECT_DIR%/new_dir/"
    }
}
``` 

Or another strategy... Not 100% sure, so that's why I'd like to see other ideas maybe 😄
