### ISSUE TITLE
Missing engines key in the framework config after twig installation

### ISSUE THREAD

**Issue by olix21** [symfony/recipes#320]
A few bundles are not working with flex because of a missing `template` service dependency.

Adding

```
framework:
    templating:
        engines: twig
```

in the `framework.yaml` will fix that. 

Is it something missing from the twig bundle recipe?

**Comment by fabpot** [comment]
As of Symfony 3.4, we recommend to use Twig directly instead of the Templating abstraction. The default recipes enforces this rule. You can add this configuration if you really need to.
