### ISSUE TITLE
symfony/flex recipe uninstallation may kill git repository

### ISSUE THREAD

**Issue by weaverryan** [symfony/recipes#324]
I like that the symfony/flex recipe creates a `.git` repository if there is none. But... if you uninstall it (edge case... but I just *totally* did this), the uninstall *removes* your `.git` directory.

Is this possibly an edge-case we could code around for in Flex? Basically, *don't* run the reversal for this one thing?

**Comment by stof** [comment]
We might rather have Flex running `git init` at the end of creating a project instead of storing the structure of a git repo in the recipe (which would avoid having gitignore files inside `.git` btw).
thus, `git init` creates more files that what we have in the recipe currently.

**Comment by BPScott** [comment]
I was in the process of upgrading a symfony-standard style app to use Flex, then had to jump back to a branch in the old style layout, I ran a composer install so I could run the old-style app and poof, no more .git folder. Whoops.

+1 for running `git init` as a post install hook to avoid having special cases where certain files get ignored

**Comment by nicolas-grekas** [comment]
IMHO, running the command is going to create a bunch of portability issues, while all a git repo is is a bunch of files/folder. Better not run git init, and prevent flex from touching the folder.

**Comment by Nyholm** [comment]
I also got my `.git` directory removed now... hm. Could we revert #312 until we got a better solution?

**Comment by javiereguiluz** [comment]
I'm proposing an alternative solution to this critical bug here: https://github.com/symfony/flex/pull/250

**Comment by lyrixx** [comment]
I'm also for not creating the initial `.git` folder.
