### ISSUE TITLE
Duplicate aliases reported on symfony.sh

### ISSUE THREAD

**Issue by weaverryan** [symfony/recipes#325]
There's a visual problem on symfony.sh:

1) Search for security
2) You will see that there are *two* packages that report that they have the alias `security`: `symfony/security-bundle` and `security/security`.

You can see this also by searching "serializer". On the Flex server, it appears that the "custom" alias from the recipe overrides the "automatic" one from being a Symfony component. It's simply that it's not reported correctly on the site (I got a bit confused today!)

Cheers!

**Comment by Nyholm** [comment]
That is true. I did not know that. But is it really an issue? I would always prefer the SecurityBundle over the security component. Same with SerializerBundle. 

It is the bundle that is being installed: 

<img width="646" alt="screen shot 2017-12-23 at 11 33 01" src="https://user-images.githubusercontent.com/1275206/34318976-3c3e39b4-e7d5-11e7-9238-ed80b577c679.png">

**Comment by weaverryan** [comment]
It’s only a display issue on Symfony.sh. When you look at the security/component package there, it should not advertise that it has a “security” alias - the security alias (as you point out) truly belongs to the bundle.

The fix is just to stop displaying that certain components have an alias, when actually it’s been overridden.

**Comment by weaverryan** [comment]
This is not an issue anymore
