### ISSUE TITLE
Override default routes with environment specific routes

### ISSUE THREAD

**Issue by wallsfantasy** [symfony/recipes#326]
Hi,

When I add routes prefix in dev environment it will be overridden by `config/routes.yaml` as it loaded latest. The code should be around [here](https://github.com/symfony/recipes/blob/ba28f5a1cc3cca92d31c0a16788dcc91f2cf7807/symfony/framework-bundle/3.3/src/Kernel.php#L59).

I'm not sure if it is expected, should proper sequence following this ..?
1. `config/routes/*`
2. `config/routes.yml'`
3. `config/{env}/routes.yml`

Please bear with my English :sweat_smile:

**Comment by Pierstoval** [comment]
The order is the following, according to the kernel:

* `config/routes/*.{php,xml,yaml,yml}`
* `config/routes/{env}/**/*.{php,xml,yaml,yml}`
* `config/routes*.{php,xml,yaml,yml}`

Latest define routes superseed any previously defined route with the same name.

**Comment by HeahDude** [comment]
It makes sense that specific environment routes should override global ones.

**Comment by curry684** [comment]
@HeahDude in some cases yes, but the env routes are in practice provided by bundles and libraries. I should be able to override them in my global application routes. It starts to get messy when I have my own env-specific routes that should override global routes, those do not really have a place in the default structure right now.

Then again, that's kind of exotic, and easily fixed by editing `configureRoutes` in `src/Kernel.php`.

**Comment by HeahDude** [comment]
>easily fixed by editing configureRoutes in src/Kernel.php.

Of courses, but we don't really need to override third parties routes, we can just edit files that have been copied from recipes.
But when a dev put some specific routes for env in his app, I tend think he may want to override global ones and not the other way around.

**Comment by Pierstoval** [comment]
In my biggest personal project I completely tweaked `configuredRoutes` in the kernel because I didn't like it, my project has specific needs for routing, so your needs could be an occasion to tweak it too if you need.

**Comment by wallsfantasy** [comment]
Apologies I didn't explained my case fully.

In my dev environment I have project names as path to separate vhosts similar to this..
```http://localhost/{project}/{path....}```
So, I need to prefix routes with `/{project}` only in dev enviroment.

In certain, I am using customized `configuredRoutes` and I think it's better to allow developers to control what they need in a non-customized fashion. I'm not really sure why should generalized config overrides more specific ones.

I believe we have different views of how env routes should work (and also how to work with the routes esp `configureRoutes` :laughing: )

@HeahDude 
> But when a dev put some specific routes for env in his app, I tend think he may want to override global ones and not the other way around.

Yes, you read my mind!

**Comment by curry684** [comment]
Why not just a single routing file and a URL_PREFIX env variable?

**Comment by wallsfantasy** [comment]
@curry684 Thanks for the tips. Having that said, without modifying `configureRoutes` the production will try to reach an env variable that is meant for dev configuration.

Peeking at `configureContainer` seems 
https://github.com/symfony/recipes/commit/365cb6a8195c0a6ae7cbb7621ebc87828836e175

**Comment by Tobion** [comment]
I think the current route loading order is the most flexible. If you need your env-specific routes to override other, then just put your routes that you might want to override in`{routes}/*` instead of `routes.yaml`.
Or if you are still not satified, you can always change things in the kernel.
