### ISSUE TITLE
Missing serialization recipe

### ISSUE THREAD

**Issue by e-moe** [symfony/recipes#33]
Consider using serialization bundles e.g. https://github.com/schmittjoh/JMSSerializerBundle

**Comment by javiereguiluz** [comment]
In the main repo we have a recipe for serializer: https://github.com/symfony/recipes/blob/master/symfony/serializer/3.3/manifest.json  It may be more advanced though.

About your proposal, we can't use JMS* bundles because of the non-MIT license they use.

**Comment by e-moe** [comment]
Oh, I see. Thanks for you answer
