### ISSUE TITLE
symfony/phpunit-bridge removes phpunit.xml.dist

### ISSUE THREAD

**Issue by mhujer** [symfony/recipes#346]
1) install `phpunit/phpunit` (it creates `phpunit.xml.dist` and some other files, commit all the changes)
2) install `symfony/phpunit-bridge`
3) uninstall it (`compose remove --dev symfony/phpunit-bridge`)

**Result:** `phpunit.xml.dist` which was not created by `symfony/phpunit-bridge` (and I updated it manually) is removed anyway.

**Comment by uikolas** [comment]
For me the questions it's. After installing symfony/phpunit-bridge i need to install phpunit/phpunit? Yes? Then why it suggest to remove it? https://github.com/symfony/recipes/blob/master/phpunit/phpunit/4.7/post-install.txt

**Comment by weaverryan** [comment]
Actually, that’s not correct :). The phpunit bridge is an alternative to phpunit. It does *use* phpunit behind the scenes, but not as a dependency in your project (it downloads phpunit itself into a directory when you run it).

So, *only* install the phpunit bridge.

About the original issue, I think it’s a “won’t fix” situation. It’s valid, but I don’t think there are plans to track which files a recipe actually created versus already existed. So Flex relies on the user using version control to make sure these edge cases aren’t *actually* destructive.

**Comment by nicolas-grekas** [comment]
What @weaverryan wrote: use version control.

**Comment by jedrzej-danko** [comment]
This odd behaviour broke our CI/CD pipeline for few hours. The scenario in CI/CD is:
- clone the repository (which contains modified phpunit.xml.dist)
- install dependencies (composer deletes phpunit.xml.dist)
- run tests (fail: because of missing configuration phpunit doesnt work properly)
@nicolas-grekas, as you see, using version control does not help.

**Comment by nicolas-grekas** [comment]
This issue should be fixed in recent versions of flex.
