### ISSUE TITLE
Add check.php to gitignore for requirements-checker package

### ISSUE THREAD

**Issue by abenettt** [symfony/recipes#348]

**Comment by fabpot** [comment]
I don't understand why you'd like to do this. Anyway, I don't think this is a good idea. Whenever you're done with the checker, remove it via Composer.

**Comment by javiereguiluz** [comment]
@abenettt in the Symfony Docs it's explained a bit better: https://symfony.com/doc/current/reference/requirements.html  After you install and run the requirements checker, you must uninstall it because it's useless for the project. Thanks!

**Comment by abenettt** [comment]
If one would only add this as a dev dependency one could just check without installing it again and it would not matter for the production deployment as it is just a dev dependency.

**Comment by javiereguiluz** [comment]
It's not a dev or prod dependency ... it's a "one-time dependency". You install it, run it ... and quickly uninstall it when you are done.
