### ISSUE TITLE
bin/console does not allow --env=prod

### ISSUE THREAD

**Issue by nesl247** [symfony/recipes#350]
bin/console does not currently allow --env=prod. It only bypasses the dotenv check if APP_ENV is set. Is there a purpose to --env anymore?

https://github.com/symfony/recipes/blob/41272ce16283fae0451b00b68a5588d181263dc4/symfony/console/3.3/bin/console#L18-L23

**Comment by weaverryan** [comment]
To be clear: it’s that the env flag *does* set the environment, it’s just that, when it’s set the prod, the .env file *is* still loaded, and that’s the weird behavior. Is that right?

**Comment by curry684** [comment]
It's the other way around.

1. The `.env` file is *only* loaded if `APP_ENV` (and thus supposedly the rest of the environment) was not provided in another way (webserver config, Docker etc.).
2. Then in https://github.com/symfony/recipes/blob/41272ce16283fae0451b00b68a5588d181263dc4/symfony/console/3.3/bin/console#L26 the `--env` parameter is extracted, and **ONLY** falls back to the env variable if not set explicitly.

So yes, `--env=prod` still works as it always did. It's purpose is still to determine which configuration to use for your application.

**Comment by xabbuh** [comment]
closing here as there is nothing to fix as explained above

**Comment by nesl247** [comment]
I just remembered why I opened this ticket. The point is that if `--env` is passed, and `APP_ENV` is not set, it should bypass the `APP_ENV` check.

The `APP_ENV` check should only take place if `--env` is not passed in at all. Using this command argument is explicitly telling the application which environment to run in.

**Comment by stof** [comment]
why ? If APP_ENV is not set, the code currently assumes that *other* env variables might not be set either, and loads the `.env` file for that. That looks like a reasonable assumption.

The `.env` file is not only about knowing which env we want to use.

**Comment by nesl247** [comment]
Maybe it's our particular case. In the Dockerfile, I build the cache already. However, I don't put the ENV there as we use the same images for multiple environments. So I don't want to set an ENV that won't be overridden using .env in local development.

It's cache:clear that is my particular use case for this.

I don't care during cache:clear that other variables are not there, as Symfony will use default values.

**Comment by curry684** [comment]
You do realize your cache will almost always be corrupt if it was generated with different environment settings than it will be used with at runtime?

That scenario is highly error prone and therefore not supported.

**Comment by nesl247** [comment]
Why would cache be corrupt when DB username/passwords change, and misc. environment variables change? It's the entire reason variables aren't hardcoded during compile time in the container.

**Comment by curry684** [comment]
You could be caching data from the wrong database, generating proxies to a wrong server or with a wrong configuration, and a zillion other things depending on what bundles you use. Container compilation and cache warming are highly volatile if not 101% certainly done on the same environment the container and cache will be used in.

**Comment by Pierstoval** [comment]
@nesl247 Some environment vars indeed can't be changed at runtime without complications, like the Doctrine ones, or the vars you inject in the Routing configuration (because the routing doesn't ask env vars at runtime, they're written in the router files at runtime and never changed unless cache is cleared).
So the "safeness" of dynamic parameters in the container is only guaranteed when they're not compiled once by the components that will use them (which is the case for Doctrine and for the Routing component).
