### ISSUE TITLE
Why GIT ignoring .php_cs config file ?

### ISSUE THREAD

**Issue by alterphp** [symfony/recipes#352]
Team developers should share the same code style config when working the same repository, or ... why should not they ?

**Comment by julienfalque** [comment]
By default, PHP CS Fixer looks for `.php_cs` and `.php_cs.dist` files, like e.g. PHPUnit does with `phpunit.xml` and `phpunit.xml.dist`. In such case, only `*.dist` files should be tracked.

**Comment by javiereguiluz** [comment]
I agree with @alterphp and I asked for that in the past but was rejected. It's common to make changes in PHPUnit config, so using phpunit.xml and phpunit.xml.dist is natural. But if the project includes a . php_cs config file, you should never change it to match your preferences. That'd be wrong and rude to your workmates. So I don't understand why you need a php_cs and php_cs.dist.

**Comment by fabpot** [comment]
I agree with you, but that's something that needs to be discussed upstream. Here, we are only dealing with configuration with what upstream decides to do :) So, closing it now.

**Comment by alterphp** [comment]
I did not know that .php_cs.dist was considered at runtime. So it's ok, I can work that way.

In order to find a better way to name files, I really like the config file names of docker-compose :
- docker-compose.yml (required at least or no config file is considered)
- docker-compose.override.yml that is combined to docker-compose.yml and allows to override some default configs
- docker-compose.yml.dist is ignored, it's, just a template to start

Thanks for your answers !

**Comment by keradus** [comment]
> But if the project includes a . php_cs config file, you should never change it to match your preferences. That'd be wrong and rude to your workmates. So I don't understand why you need a php_cs and php_cs.dist.

@javiereguiluz , let us compare the config to PHPUnit.
what config file specifies? at PHPUnit - what file to test. but one could create his local config, where he could apply some extra listeners, preconfigure env variable or system config.
same, at PHP CS Fixer, in config we do have for sure configured ruleset and style, and as you said, it shall not be modified at hoc. But, it does also contain "local" config - like caching, progress bar, used reporting format and even path to php executable - in other words, things that are up to single dev or his env.

I you feel that "common" part and "single-dev" part shall be 2 different config, or you want to propose a better way of handling the configuration, please raise a concern at PHP CS Fixer directly, as Fabien suggested.
For now, sharing `.php_cs.dist` and git-ignoring `.php_cs` is current best practice, so recipe follows it.
