### ISSUE TITLE
Where is symfony/doctrine-bridge ?

### ISSUE THREAD

**Issue by sfeni** [symfony/recipes#358]
Hi,

on https://symfony.sh I find symfony/doctrine-bridge with official badge.
But I cannot find it inside the git repo.
Where is the recipe? Gone? Hidden? Has someone deleted it?

Thanks

**Comment by Pierstoval** [comment]
Why do you need a recipe for `symfony/doctrine-bridge`? Config is already available for the DoctrineBundle. The bridge doesn't need a recipe.

**Comment by sfeni** [comment]
Thats not the question. Why is there a recipe on symfony.sh but it is not in the git repo!?
If it does not need a recipe why is there one?

**Comment by jvasseur** [comment]
`symfony/doctrine-bridge` doesn't have have a recipe on symfony.sh, it only appears on the site because there is an alias from `doctrine-bride` to `symfony/doctrine-bride` (all packages in the symfony packagist namespace get a "free" alias like this).

**Comment by Pierstoval** [comment]
It's only because it has an alias.

By default, every `symfony/{name}` package is aliased to `name` to simplify requiring a Symfony dependency.

It's just to allow you to write `composer req doctrine-bridge` instead of `composer req symfony/doctrine-bridge`, that's all.

**Comment by sfeni** [comment]
Ah, thank you!
