### ISSUE TITLE
Can't use Doctrine/DBAL in production

### ISSUE THREAD

**Issue by QuentinCurtet** [symfony/recipes#373]
Hi,

When i change my env to production, i have the white page with an error in my log : 
`PHP Fatal error:  Uncaught LogicException: To configure the ORM layer, you must first install the doctrine/orm package.`

Is there any way to use the DBAL without the ORM in production ?

Thanks for the help.

**Comment by xabbuh** [comment]
You probably at least need to remove the ORM related config: https://github.com/symfony/recipes/blob/master/doctrine/doctrine-bundle/1.6/config/packages/prod/doctrine.yaml#L2-L11

**Comment by QuentinCurtet** [comment]
Ok, in fact it fixed my problem ^^
Thanks !
