### ISSUE TITLE
[RFC] Data Fixture

### ISSUE THREAD

**Issue by lyrixx** [symfony/recipes#375]
When installing DoctrineFixturesBundle with flex, the folder `src/DataFixture` is created, but empty.

I think we could improve the DX by creating the `AppFixture` files.
One could argue we don't do that form controller and co, but in the doc we do recommend to use only one fixture file (eventually one per env).

WDYT?

**Comment by Nyholm** [comment]
Fixtures could be a really strange thing if you've never seen them before. Im 👍 for better DX.

**Comment by lyrixx** [comment]
Fixed by #480
