### ISSUE TITLE
[Proposal] Run script once after configuring a recipe

### ISSUE THREAD

**Issue by slootjes** [symfony/recipes#378]
I know we have _composer-scripts_ option in a recipe but some things I just need to run once after the bundle is configured by the recipe. For instance I've got a recipe which includes Defuse library to work with encryption and I'd like to generate a key automatically so it's ready for use. The same applies to a custom recipe for Sonata Admin where I'd like to automatically generate admin users and to setup security rules.

I could use the _composer-scripts_ option with a "encryption::assert-key" or something which runs every time but it sounds like a workaround so I want to propose a _composer-scripts-once_ option where I can define scripts that should just run once after installation. I'm sure I can provide a PR myself for this when this idea is approved.

**Comment by Pierstoval** [comment]
I'm not sure _executing commands_ in the name of the user is a good idea.

However, I recommend you to use the `post-install.txt` file to tell the user _how to create a key_, because there is not "one way to do it", and a key can be generated in several ways.

**Comment by slootjes** [comment]
When using Defuse there is just 1 way to do it so that's why I like to remove the requirement for the user to do custom stuff and prefer that the recipe takes care of this instead. But this is just an example, I'm sure other have multiple use cases where this could come in handy.

**Comment by Pierstoval** [comment]
Having a script being executed _only once_ is more opinionated because you can't prevent it to be executed (unless you take care of the `--no-scripts` option).

Having it in `composer-scripts` still allow you to run flex with `--no-scripts` and remove it from `composer.json` afterwards.

If there is only one single way to do it, instead of using the `post-install.txt` text, I would them recommend to add it to `composer-scripts` and the command must make sure to keep existing files, and not overwrite them, to avoid the script to replace an existing key and potentially break the app.

**Comment by slootjes** [comment]
Thanks for explaining. For now I've created the recipe which adds a command to _composer-scripts_, the script then does it's thing and removes itself from _composer-scripts_ again. For this I'm simply using the configurators from Flex so it works like a charm. It's not the prettiest solution perhaps but it does the job very well to have a good DX for an internal recipe.

**Comment by Nyholm** [comment]
Thank you @Pierstoval. I take it that @slootjes solved his problem. I'm will close this issue now. If you really feel it should be open just say so and I'll reopen it.

**Comment by slootjes** [comment]
It would still be nice if someone else had an idea. There are just some things which are currently not possible with recipes which only need to run once to finish. Would like to see a solution for this so I'm open for others suggestions thats why I prefer to keep this open.

**Comment by nicolas-grekas** [comment]
Closing as this staled.
Maybe maker-bundle is the right approach.
