### ISSUE TITLE
prod doctrine cache configuration

### ISSUE THREAD

**Issue by Gemorroj** [symfony/recipes#388]
https://github.com/symfony/recipes/blob/ff028103ab921596a37c3318576798ac29971926/doctrine/doctrine-bundle/1.6/config/packages/prod/doctrine.yaml
for cache uses `DoctrineProvider` and `FilesystemAdapter` (service `cache.app`)  or `FilesystemAdapter`/`PhpFilesAdapter`/`ChainAdapter` (service `cache.system`) .
Why not use `apcu` as it was in symfony 3? https://symfony.com/doc/current/reference/configuration/doctrine#caching-drivers
Please explain or document this behavior from Symfony flex recipe.

**Comment by weaverryan** [comment]
It’s mostly a standardization. There are two types of cache in Symfony - app & system. The user can then configure each of these (well, system is probably ok as is) to use whatever backend they want.

In this recipe, we re-use the app and system caches. This means that you only need to configure one cache adapter (for app) and everything else uses it. This config also works for everyone out of the box: there’s no guarantee apcu exists.

I hope that explains! Just configure you app and system caches (if you want to) and everything will automatically use that: just one place to configure things :).

**Comment by Gemorroj** [comment]
I uncomment `app: cache.adapter.apcu` in `config/packages/framework.yaml`, and now i see:
```text
DoctrineProvider {#9997 ▼
  -pool: TraceableAdapter {#10154 ▼
    #pool: ChainAdapter {#5995 ▼
      -adapters: array:2 [▼
        0 => ApcuAdapter {#8832 ▶}
        1 => FilesystemAdapter {#5279 ▶}
      ]
      -adapterCount: 2
      -saveUp: Closure {#5460 ▶}
    }
    -calls: array:2 [▶]
  }
  -namespace: ""
  -namespaceVersion: 1
}
```
i not understand this... 
why used `ApcuAdapter` **and** `FilesystemAdapter`? I only indicated `apcu`.
and for `app.system` service i see:
```text
DoctrineProvider {#4950 ▼
  -pool: TraceableAdapter {#9794 ▼
    #pool: FilesystemAdapter {#5202 ▶}
    -calls: []
  }
  -namespace: ""
  -namespaceVersion: null
}
```
but in `vendor/symfony/framework-bundle/Resources/config/cache.xml`
```xml
<factory class="Symfony\Component\Cache\Adapter\AbstractAdapter" method="createSystemCache" />
```
```php
    /**
     * @param string               $namespace
     * @param int                  $defaultLifetime
     * @param string               $version
     * @param string               $directory
     * @param LoggerInterface|null $logger
     *
     * @return AdapterInterface
     */
    public static function createSystemCache($namespace, $defaultLifetime, $version, $directory, LoggerInterface $logger = null)
    {
        if (null === self::$apcuSupported) {
            self::$apcuSupported = ApcuAdapter::isSupported();
        }

        if (!self::$apcuSupported && null === self::$phpFilesSupported) {
            self::$phpFilesSupported = PhpFilesAdapter::isSupported();
        }

        if (self::$phpFilesSupported) {
            $opcache = new PhpFilesAdapter($namespace, $defaultLifetime, $directory);
            if (null !== $logger) {
                $opcache->setLogger($logger);
            }

            return $opcache;
        }

        $fs = new FilesystemAdapter($namespace, $defaultLifetime, $directory);
        if (null !== $logger) {
            $fs->setLogger($logger);
        }
        if (!self::$apcuSupported) {
            return $fs;
        }

        $apcu = new ApcuAdapter($namespace, (int) $defaultLifetime / 5, $version);
        if ('cli' === \PHP_SAPI && !ini_get('apc.enable_cli')) {
            $apcu->setLogger(new NullLogger());
        } elseif (null !== $logger) {
            $apcu->setLogger($logger);
        }

        return new ChainAdapter(array($apcu, $fs));
    }
```
and i really have enabled `apcu`, but `app.system` use filesystem.


The problem comes from the fact that I cannot use `getStats` and cannot monitor the cache status.
`DoctrinePriver` suppresses the statistics. And no access to pool.

**Comment by Tobion** [comment]
If you found a bug please try to give a reproducer. For questions I have to refer you to https://symfony.com/support Thank you.
