### ISSUE TITLE
Documentation unclear about recipe only registering bundle

### ISSUE THREAD

**Issue by magnetik** [symfony/recipes#394]
> Don't create a recipe for Symfony bundles if the only configuration in the manifest is the registration of the bundle for all environments, as this is done automatically.

Is this intended for "symfony bundles" as "bundles with the `symfony/` vendor" or just all bundles?

Thanks

**Comment by Pierstoval** [comment]
A Bundle is always for Symfony, so Symfony bundles are just bundles for Symfony, not only bundles _made_ by Symfony 😉 

IIRC, there is no other PHP framework using the name "bundle" for its logic
