### ISSUE TITLE
[RFC] Use config node path as filename for recipes which are not root nodes

### ISSUE THREAD

**Issue by phansys** [symfony/recipes#396]
With this RFC, I want to propose that recipes containing configuration for sub nodes have a name according that node. By instance, configuration file for [symfony/translation](https://github.com/symfony/recipes/blob/master/symfony/translation/3.3/config/packages/translation.yaml#L3) recipe should be named `framework.translator.yaml`.
The main reason I'm proposing this, is based in the following assumption / idea / example about the current behavior:

1- Configuration files under "config/packages/" dir are mapped to packages (bundles), and you would expect the whole configuration for a single package be included in a single configuration file.
2- You already have declared configuration for subnodes at `framework.yaml`, including `framework.translator` node.
3- You install a recipe which ignore completely the already configured path and will install duplicated configuration for `framework.translator` node in `config/packages/translation.yaml`

For these reasons, I think it would be better to expose sub-node recipes with filenames that makes the node inheritance clear.

**Comment by weaverryan** [comment]
Hmmm. That makes sense to me :)

**Comment by OskarStark** [comment]
Nice idea, but it would be better if flex could merge such files together in framework.yaml and outputs a warning if such node exists and allow the user to overwrite or cancel it

**Comment by fabpot** [comment]
👎 as explained in the related PR.
