### ISSUE TITLE
framework-bundle Do not install assets with "--symlink --relative" by default

### ISSUE THREAD

**Issue by gaiaz-iusipov** [symfony/recipes#398]
For some reason, there are "--symlink --relative" by default.

- Docker with Nginx has mounted only `public` directory, but not `vendor`, so vendor bundles with assets become unavailable for nginx;
- Windows symlink issues.

`recipes/symfony/framework-bundle/3.3/manifest.json`
```
    "composer-scripts": {
        "cache:clear": "symfony-cmd",
        "assets:install --symlink --relative %PUBLIC_DIR%": "symfony-cmd"
    },
```

**Comment by covex-nn** [comment]
I agree with @gaiaz-iusipov, and without modification in `composer.json` this could be fixed only by sharing `vendor` directory from `php` container to `nginx` container, but it is not right! Nginx container shoud only has access to assets.

I work under Windows, and symlinks are not created as relative. They are absolute, and point to`C:\ ...`. So, even if i would share `vendor` dir, Nginx will not have access to these files: inside containers symlinks still point to somewhere `C:\ ...`. And only when i run `composer auto-scripts` inside container, symlinks start to point to `../../vendor/ ...`
