### ISSUE TITLE
[DebugBundle] bundle is not configured in test env

### ISSUE THREAD

**Issue by garak** [symfony/recipes#418]
Bundle is configured to be enabled in dev and test environments, but it's enabled in dev only.
So you end up trying to dump inside a test and seeing nothing in debug server.
This is a DX problem, mainly for developers coming from older Symfony versions, where enabling something in dev was automatically enabling in test also.
Recipe should copy yaml configuration in `config/packages/test` dir.

**Comment by maxhelias** [comment]
I think your issue is related to this PR #417

**Comment by garak** [comment]
@maxhelias how it's related?

**Comment by maxhelias** [comment]
Oh yes, sorry, I misinterpreted the need

**Comment by nicolas-grekas** [comment]
Fixed by #940 I guess.
