### ISSUE TITLE
If APP_DEBUG=false it will return true

### ISSUE THREAD

**Issue by atillay** [symfony/recipes#433]
https://github.com/symfony/recipes/blob/c2941dc110fb3edb27081260b6d3ad4996f46a0a/symfony/framework-bundle/3.3/public/index.php#L19

When using (bool) "false" it returns true
When using (bool) "0" it returns false

Maybe I should always use 0 or 1 in my environment file ?

**Comment by Pierstoval** [comment]
You should use `APP_DEBUG=0`, basic env var handling 😉
