### ISSUE TITLE
Where to put Sonata Bundles ?

### ISSUE THREAD

**Issue by rande** [symfony/recipes#44]
Hello ;)

Where should we put the Sonata Bundles suite ?

Thanks!

**Comment by fabpot** [comment]
I think the best would be to submit PRs on the contrib repository and then move the PR here if that makes sense (I will have a tool to automate the move of a recipe from contrib to main).

**Comment by Pierstoval** [comment]
@rande and even if you want to integrate sonata bundles, you can create Composer "meta packages" and create packs like @fabpot proposed in [his last article about SF4 and Flex](https://medium.com/@fabpot/symfony-4-a-quick-demo-da7d32be323), you could create a simple `sonata/admin` package that would require all necessary packages, and each one can have its own recipe 😄
