### ISSUE TITLE
Cannot migrate a database in the test environment

### ISSUE THREAD

**Issue by ChangePlaces** [symfony/recipes#441]
I'm unable to execute `bin/console doctrine:migrations:migrate --env=test`. Instead of a migration to an empty database I get the output `No migrations to execute.`. I have an `.env.test` in the root of the project with a separate `database_url` for the test environment.

**Comment by Tobion** [comment]
`.env.test` is only supported since https://github.com/symfony/recipes/pull/481
I guess you thought it would work like this but it didn't have any effect yet for you.
