### ISSUE TITLE
[Panther] Update recipe alias

### ISSUE THREAD

**Issue by matthieumota** [symfony/recipes#443]
Hey ! I see that all symfony/* packages have automatically aliases like security, security-acl, ... No need real recipes because not necessary to automatise installation, but alias feature is great. I see that amazing panthère library from @dunglas was renamed to Panther (Fluent :)) and I've tested ```composer require panther```, not work but ```composer require panthere``` work, maybe you can change link on symfony.sh ? I think code is only internal because we cannot see recipe for symfony/* packages.

<img width="1073" alt="capture d ecran 2018-07-24 a 20 09 25" src="https://user-images.githubusercontent.com/2427947/43157509-8933fe02-8f7d-11e8-99d9-c23bfc5cfb84.png">

**Comment by Nyholm** [comment]
The package is named `symfony/panther`
The repo is here: https://github.com/symfony/panther
Flex version: 1.0.84
There is an abandoned package named: `symfony/panthere`

Doing `composer req panther` does not work. I confirm the issue. 

I do not know why it does not work. Maybe @fabpot could have a look.

**Comment by dunglas** [comment]
It doesn't work because there are no recipes yet. My 1st intuition was to add Panther to the `test` alias: https://github.com/symfony/test-pack/pull/4
But maybe creating a dedicated alias, or doing both is a better idea.

**Comment by Nyholm** [comment]
Are you sure? I thought all symfony/* packages were automatically aliased without a recipe.

**Comment by dunglas** [comment]
I thought this auto-alias was only working for the subtree split, but I'm not sure.

**Comment by chalasr** [comment]
`security-acl` is correctly resolved as `symfony/security-acl` even if is not part of the main `symfony/symfony` repo, perhaps some flex server's cache that needs to be cleared? https://packagist.org/packages/symfony/panthere should be manually removed for sure

**Comment by fabpot** [comment]
Fixed now.
