### ISSUE TITLE
Change post-install.txt for webiste-skeleton

### ISSUE THREAD

**Issue by ismail1432** [symfony/recipes#446]
Hi Everyone, 
Whatever the Symfony dependencies is downloaded (website-skeleton or skeleton) [There is the same output text](https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/3.3/post-install.txt) with this sentence : `Run composer require server --dev for a better web server`. 
The "minor problem" is that if you have downloaded the website-skeleton you already have the WebserverBundle and nothing will happen that could be strange for newcomers.

I don't know exactly what is the "hack" to do that but IMHO for the website-skeleton the output should be something like that:

```sh
* Run your application:
    1. Change to the project directory
    2. Create your code repository with the git init command
    3. Run php bin/console server:run for a better web server
    4. Browse to the http://localhost:8000/ URL.

       Quit the server with CTRL-C.

  * Read the documentation at https://symfony.com/doc
```
I know that's not a big problem but we are always working for a better UX :+1: 
WDYT ?

**Comment by fabpot** [comment]
Web server bundle is deprecated now. Let's close.
