### ISSUE TITLE
Router strict_requirements in test env

### ISSUE THREAD

**Issue by Korikulum** [symfony/recipes#454]
In Symfony versions prior to 4 the `config_test.yml` imported `config_dev.yml`:
```yaml
# config_test.yml
imports:
    - { resource: config_dev.yml }
```
Since the `framework.router.strict_requirements` parameter was set to `true` in the dev env, the test env inherited that value.

In Symfony 4 & above, the `strict_requirements` is not `true` in the test env. Don't know if this was done intentionally, but I haven't really notice it until now & I prefer to have it set to `true` in my test env to prevent tests form passing when they shouldn't.

I know I can just add this to my test env, but perhaps it'd be good to have it set to `true` in the test env by default?

**Comment by Nyholm** [comment]
Thank you. Closed by #455
