### ISSUE TITLE
[framework-bundle] [bug] the proposed `Kernel::registerBundles` implementation is not consistent

### ISSUE THREAD

**Issue by docteurklein** [symfony/recipes#46]
`yield` ing bundle instances makes it incompatible with multiple iterations (Generators cannot be `rewind`ed once iterated, generating this kind of exceptions: 

```
bin/console config:dump framework
                                               
  [Exception]                                  
  Cannot traverse an already closed generator  
                                               

Exception trace:
 () at /home/florian/work/symfony/demo/vendor/symfony/framework-bundle/Command/AbstractConfigCommand.php:127
 Symfony\Bundle\FrameworkBundle\Command\AbstractConfigCommand->initializeBundles() at /home/florian/work/symfony/demo/vendor/symfony/framework-bundle/Command/AbstractConfigCommand.php:56
 Symfony\Bundle\FrameworkBundle\Command\AbstractConfigCommand->findExtension() at /home/florian/work/symfony/demo/vendor/symfony/framework-bundle/Command/ConfigDumpReferenceCommand.php:88
 Symfony\Bundle\FrameworkBundle\Command\ConfigDumpReferenceCommand->execute() at /home/florian/work/symfony/demo/vendor/symfony/console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at /home/florian/work/symfony/demo/vendor/symfony/console/Application.php:887
 Symfony\Component\Console\Application->doRunCommand() at /home/florian/work/symfony/demo/vendor/symfony/console/Application.php:223
 Symfony\Component\Console\Application->doRun() at /home/florian/work/symfony/demo/vendor/symfony/framework-bundle/Console/Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /home/florian/work/symfony/demo/vendor/symfony/console/Application.php:130
 Symfony\Component\Console\Application->run() at /home/florian/work/symfony/demo/bin/console:33

config:dump-reference [--format FORMAT] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<name>] [<path>]

```

I propose either to return a typical `array`, or to use `iterator_to_array` in portions of code that needs multiple iterations, or refactor the way bundles are initialized.

**Comment by sstok** [comment]
I wonder why this was even done, you are going to initialize all anyway 🤔

@nicolas-grekas You have worked with this before, can you explain why it is done here?

**Comment by sstok** [comment]
@docteurklein Thinking about this, why do load the bundles multiple times? Because it would initialize them multiple times then 😐 you can use `getBundles()` after initialization.

I guess we need to validate if the bundles are already initialized.

**Comment by docteurklein** [comment]
the problem lies here: 

https://github.com/symfony/framework-bundle/blob/343754d1d30351b4029675bf27747718a217df6d/Command/AbstractConfigCommand.php#L121-L127

Not sure yet why this is done like this

**Comment by stof** [comment]
I think it should be calling `getBundles` instead

**Comment by docteurklein** [comment]
indeed, based on what I see here: https://github.com/symfony/framework-bundle/commit/cfcfae03e902505f6d2a4127e0f3b04eef9be95f it used to call `getBundles()`
