### ISSUE TITLE
In symfony/console bin/console should make use of COMPOSER_VENDOR_DIR env var if set

### ISSUE THREAD

**Issue by olberger** [symfony/recipes#468]
(_re-filed here as https://github.com/symfony/symfony/issues/28583 wasn't the best place apparently_)

Using the COMPOSER_VENDOR_DIR env var allows to divert the location of vendor/ for composer. This is handy when for example working on a slow file-system (NFS, or virtual machine shared drive, etc.), where parsing lots of tiny PHP files isn't very much efficient.

However, bin/console relies on the autoloader being in a vendor/ subdir:
```
require __DIR__.'/../vendor/autoload.php';
```
One has to symlink vendor to the location of COMPOSER_VENDOR_DIR, which may be annoying since that dir may be reset if COMPOSER_VENDOR_DIR is diverted to a temporary location.

I guess changing bin/console so that it supports a different location, if the COMPOSER_VENDOR_DIR env var is set, would make Symfony more flexible.

Something along the lines of https://github.com/symfony/symfony/issues/28583#issuecomment-424026515 would probably make it possible.

Hope this makes sense.

**Comment by Pierstoval** [comment]
This means that it would have to be also added to `public/index.php`.

And once again, using env vars means that we should check in `$_SERVER`, `$_ENV` and `getenv()` :confused:

**Comment by olberger** [comment]
Most likely yes, for public/index.php ;-)

Actually, supporting the env var in bin/console may happen very early in the development process, long before public/index.php is ever used.

Supporting COMPOSER_VENDOR_DIR at run time may be problematic, security-wise, I guess... so it may help in dev env, but I wouldn't support it in production env maybe ?

Hope that makes sense.

**Comment by Pierstoval** [comment]
> Actually, supporting the env var in bin/console may happen very early in the development process, long before public/index.php is ever used.

`public/index.php` is used for **every** HTTP request, even the ones that are pointing at the native PHP server (like when using `bin/console server:start`), so this is why any update on the console must be ported to the HTTP front controller. After all, Symfony full-stack is an HTTP framework :wink:

**Comment by stof** [comment]
making the required path dynamic based on an env variable might be quite bad regarding OPCache as well.

**Comment by nicolas-grekas** [comment]
I think this is not common enough to be in the default recipe.
Instead, I'd suggest you patch the file after checking out if you need that.

**Comment by fabpot** [comment]
AFAIK, nobody else ever had this issue. So, I agree with @nicolas-grekas (especially as this is not trivial).
