### ISSUE TITLE
[framework-bundle] Don't advice to install web-server-bundle when already installed

### ISSUE THREAD

**Issue by sstok** [symfony/recipes#49]
I installed the web-server-bundle but I'm still getting:

```
$ make serve
Server listening on http://127.0.0.1:8000
Quit the server with CTRL-C.
Run composer require symfony/web-server-bundle for a better web server
php -S 127.0.0.1:8000 -t web
PHP 7.1.3 Development Server started at Wed May  3 14:25:01 2017
Listening on http://127.0.0.1:8000
```

It seems I need to run `bin/console server:start` instead but this is not explained.
Also no post-install is shown to tell me I need to use something else?

**Comment by stof** [comment]
@fabpot looks like the symfony/web-server-bundle manifest does not overwrite `make serve`

**Comment by sstok** [comment]
I don't think it's possible to overwrite this 🤔 but it should be possible to detect if this command is installed and then show a different message.

**Comment by fabpot** [comment]
PR welcomed :) I think `make serve` should then run `server:run`.

**Comment by sstok** [comment]
What's the best way to detect if this command is installed?
server:status gives error code 1 when the server is not running, but when the command is not installed it also gives this error 🤔

**Comment by fabpot** [comment]
`./bin/console list server | grep server:run`?

**Comment by sstok** [comment]
Ah yes 😋

**Comment by sstok** [comment]
OK, Makefiles are something I really need to learn 😑

This doesn't work, and the error `/bin/sh: -c: line 1: syntax error: unexpected end of file` is anything but helpful.

```bash
serve:
	@if [ -f bin/console ] && [ bin/console list server | grep server:run ]; then
		bin/console server:start
		@echo "Quit the server with bin/console server:stop."
	@else
		@echo "\033[32;49mServer listening on http://127.0.0.1:8000\033[39m"
		@echo "Quit the server with CTRL-C."
		@echo "Run \033[32mcomposer require symfony/web-server-bundle\033[39m for a better web server"
		php -S 127.0.0.1:8000 -t web
	@if
```

**Comment by sstok** [comment]
OK, I'm starting to loose my nerve here... 💀 Make is doing a great at make**ing** me become really angry, I give-up!! WHY CAN'T YOU DEFINE A SINGLE IF STATEMENT?!!

**Comment by stof** [comment]
I'll try to look at this, as I want to play with the Makefile to solve #50 anyway.

**Comment by fabpot** [comment]
fixed a while ago
