### ISSUE TITLE
An error during cache warmup displays the message that symfony/console is needed

### ISSUE THREAD

**Issue by stof** [symfony/recipes#50]
The cache warmup command currently looks like this in the Makefile:

```
@test -f bin/console && bin/console cache:warmup || echo "cannot warmup the cache (needs symfony/console)"
```

The issue with this is that the message will be displayed in 2 cases:

- when `@test` fails due to the console not being there (which is the case we want)
- when the `bin/console cache:warmup` command fails due to an error if your project

And another effect of this is that `make cache-warmup` can never fail:

- without the console, it fails to warmup but still exits with 0
- in case of warmup failure, it displays the message badly and again exits with 0.

The second case clearly must exit with a failure exit code.
For the first case, I think it should too, but this can be discussed.

**Comment by fabpot** [comment]
Closing as the Makefile has been heavily modified since then.
