### ISSUE TITLE
Bad error message if you set APP_EN=prod and pass --env=prod

### ISSUE THREAD

**Issue by weaverryan** [symfony/recipes#500]
As discussed on #497, if you set `APP_ENV` and also pass `--env=prod`, the `--env=prod` effectively makes it look like your `APP_ENV` env var is not set, and so it follows the normal logic of loading the `.env` files. That's the expected behavior.

However, the error is misleading. If you run:

```
APP_ENV=prod bin/console cache:clear --env=prod
```

You'll get the error:

> The "APP_ENV" environment variable is not set to "prod". Please run "composer require symfony/dotenv" to load the ".env" files configuring the application.

This error is correct, *except* for this exact situation: when in fact `APP_ENV` IS set, but its behavior is being overridden by `--env=prod`. How about (for this one situation), the error is:

> Because you passed `--env=prod`, the DotEnv component is trying to load your ".env" files., but that component is not installed. Please run "composer require symfony/dotenv" to load the ".env" files or set an `APP_ENV=prod` environment variable and remove the `--env=prod` flag to avoid loading these files.

A little wordy... but what do you think? The tricky part is that it requires passing some "flag" from `bin/console` into `config/bootstrap.php` so that we know that `--env=prod` was set.

**Comment by hackzilla** [comment]
That would work for me.
Better than the existing misleading wording.

**Comment by nicolas-grekas** [comment]
Still relevant ?

**Comment by lukey78** [comment]
Just stumbled upon this on deploying my first Symfony 4 app to a server and running a cronjob there where I set --env=prod as I did with Symfony 3. The error message is very misleading. And if you follow the many advices to install dotenv as a prod dependency, you're doing something wrong.

**Comment by Tobion** [comment]
Closing as APP_ENV=prod bin/console cache:clear --env=prod does not give the error anymore.
