### ISSUE TITLE
Dotenv loadEnv() method not available

### ISSUE THREAD

**Issue by PaddyLock** [symfony/recipes#505]
symfony/framework-bundle v4.1.9

In https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/4.2/config/bootstrap.php

Dotenv())->loadEnv(dirname(__DIR__).'/.env'

loadEnv() method is not available. Should it be load()

**Comment by chalasr** [comment]
You should not use the 4.2 version of the `framework-bundle` if you are not using symfony/framework-bundle v4.2. Use the [previous version](https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/3.3) or upgrade your application to Symfony 4.2 instead.

**Comment by PaddyLock** [comment]
I needed to upgrade to 4.2
