### ISSUE TITLE
bootstrap.php breaks when running PHPUnit

### ISSUE THREAD

**Issue by cameronmurphy** [symfony/recipes#512]
On a vanilla install of Symfony 4.2, running PHPUnit fails with the error `Undefined index: APP_ENV`. I traced the issue down to the use of elvis operators instead of null coalesce operators (used on the next line) in [config/bootstrap.php](https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/4.2/config/bootstrap.php#L19).

I was able to resolve by changing
```php
$_SERVER['APP_ENV'] = $_ENV['APP_ENV'] = $_SERVER['APP_ENV'] ?: $_ENV['APP_ENV'] ?: 'dev';
```
to
```php
$_SERVER['APP_ENV'] = $_ENV['APP_ENV'] = $_SERVER['APP_ENV'] ?? $_ENV['APP_ENV'] ?? 'dev';
```
in config/bootstrap.php.

Steps to reproduce (tested with CentOS 7, PHP 7.2.13, Symfony CLI 4.2.2)
```
$ symfony new --full test
$ cd test
$ bin/phpunit
```

**Comment by xabbuh** [comment]
Same as symfony/symfony#29771?

**Comment by ro0NL** [comment]
Confirmed. Using `?:` doesnt handle undefined indexes: https://3v4l.org/MvGV0

**Comment by rsukonovs** [comment]
Updated from 4.1 to 4.2 and run into same problem.

**Comment by Pierstoval** [comment]
What about using `empty()` which should handle undefined indexes?

**Comment by fabpot** [comment]
`empty()` should never be used.

**Comment by Pierstoval** [comment]
Any particular reason for that?

**Comment by javiereguiluz** [comment]
@Pierstoval we (usually) don't use `empty()` in Symfony code because most of the times you want to only check `null === ...` and not empty strings or zeros. Sometimes you want to test everything ... but `empty()` is too "liberal" and that's why we usually prefer to be explicit in the conditions.

**Comment by weaverryan** [comment]
See #513

**Comment by AkashicSeer** [comment]
Alright so how do I fix this?

**Comment by gmsantos** [comment]
@AkashicSeer are you having the exact same issue? Didn't #513 worked for you?
