### ISSUE TITLE
reinstall recipe

### ISSUE THREAD

**Issue by kricha** [symfony/recipes#516]
Hello,

is there way to reinstall recipe? For example for updating console or index.php file?

**Comment by Pierstoval** [comment]
For now, there are a few ways:

• Run `composer rem package && composer req package`, this will remove and re-install the package and its recipe.
• Remove the corresponding package reference in the `symfony.lock` file and run `composer sync-recipes`

**Comment by stof** [comment]
The dev version of Flex (not released yet) has a `composer sync-recipes --force` command for that purpose.

**Comment by kricha** [comment]
Thanks!
