### ISSUE TITLE
Adding route and Controller for "welcome" page in framework bundle recipe

### ISSUE THREAD

**Issue by petr-buchin** [symfony/recipes#52]
I think DefaultController should be added for displaying "welcome page" after installation. 
At the moment if user follows [quick demo tutorial](https://medium.com/@fabpot/symfony-4-a-quick-demo-da7d32be323) by @fabpot, runs webserver and opens http://localhost:8000/ - he sees 404 Exception page.

**Comment by sstok** [comment]
Related to https://github.com/symfony/flex/issues/20

**Comment by fabpot** [comment]
Closing as a duplicate of symfony/flex#20
