### ISSUE TITLE
env.local.php no composer script for generate

### ISSUE THREAD

**Issue by mhf-ir** [symfony/recipes#522]
Why useless Error Control Operators ?
There is no such composer script for generate it.
`composer dump-env prod` ??

It's good to have php file instead dot.env file but how could we generate that php file?

https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/4.2/config/bootstrap.php#L9

**Comment by Pierstoval** [comment]
It's coming in Flex very soon, check symfony/flex#449 😉

**Comment by nicolas-grekas** [comment]
Note that `composer dump-env prod --empty` allows completely ignoring .env files if that's what you want.
