### ISSUE TITLE
why not let a recipe stays in its package instead of a central place? 

### ISSUE THREAD

**Issue by videni** [symfony/recipes#53]
the former has a few advantages than the second one

1. No need to add a version like `recipes/symfony/framework-bundle/3.3/`. the version here implies us this recipe is valid for >=3.3.  I think this is not necessary. the package we declare in composer.json should have valid recipe in it.  flex just uses that recipe of that specific version.  

2. According to  current design , we have two repositories for recipes,  `recipes-contrib` and `recipe` repo , once  a  contributed package released new version, we have to push new PR to `recipes-contrib` repo, then the manage of `recipes-contrib` repo needs to merge that PR.  this work is also not necessary. 

A central place to discover  Symfony flex compatible  packages is  better than central place for recipe, the recipe itself should be maintained by developers of that package,  it is born with that package, also fall with that.  the `NPM` and 'Yarn' might be a good example we can follow.

**Comment by fabpot** [comment]
Many features I want to add need a central repository. But even today, that's a must.

Even a basic feature like removing a package needs more than a local recipe as the recipe might have evolved between the time you installed it and the time you are removing it.

Moreover, the fact that we curate the recipe and validate them is an important part of the process and the value we want to propose. I don't want packages to be able to do anything they want.

Last, but not least, the recipes repository is not just for Symfony bundles, but for any Composer packages (like PHPUnit, Twig or Swiftmailer). For these packages, I doubt that their maintainers will want to add some specific Symfony recipes.
