### ISSUE TITLE
Unable to use getenv when using .env.local.php

### ISSUE THREAD

**Issue by toddcarver** [symfony/recipes#532]
I'm not sure if this is an issue, so I apologize in advance if I am mistaken.  We just upgraded to 4.2 and have implemented config/bootstrap.php as recommended here:

https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/4.2/config/bootstrap.php

We have created .env.local.php so the block below is evaulated:

```
if (is_array($env = @include dirname(__DIR__).'/.env.local.php')) {
    $_SERVER += $env;
    $_ENV += $env;
}
```

The problem is that all our calls using getenv are broken.  After researching I believe this is because the env vars are not loaded via Dotenv, which adds the env vars to $_ENV and by using putenv. Using getenv works if the following block runs:

```
} else {
    // load all the .env files
    (new Dotenv())->loadEnv(dirname(__DIR__).'/.env');
}
```

Any help you can offer with a recommendation to resolve this would be greatly appreciated.  Thank you.

**Comment by nicolas-grekas** [comment]
Hum, yes, that's a limitation of using the compiled
.env file.
My recommendation is to not use `getenv()`: it's not thread safe so using it can break randomly on some machines, it's slower, and DI configuration is more flexible...

**Comment by toddcarver** [comment]
Thanks, Nicolas. I will close the issue.

**Comment by nicolas-grekas** [comment]
> can't we merge the values stored in $_SERVER with the values dumped in the .env.local.php?

that's exactly what should happen already, dumped values should always be defaults and should never override existing real vars. Please provide a reproduce if that's not what you experience.

**Comment by benja-M-1** [comment]
I dove a little bit more with this php script

```php 
<?php

$key = 'foo';
$value = 'bar';
$_SERVER[$key] = $value;

if (is_array($env = include __DIR__.'/.env.local.php')) {
    $_SERVER += $env;
    $_ENV += $env;
}

var_dump([count($_ENV), count($_SERVER), getenv($key, true)]);
```
and the following value of `.env.local.php`

```php
<?php

return array (
  'APP_ENV' => 'baz',
);
```
Here is the result:
![image](https://user-images.githubusercontent.com/212269/55826796-119f5a00-5b09-11e9-84fb-329f252af89d.png)

It seems that `$_ENV` is empty at start and thus `getenv('foo)` , which I think  `EnvVarProcessor::getEnv` uses, returns `baz`. That's why I have my issue.

@nicolas-grekas Don't you think that `Dotenv::load` should be used here instead of adding `$env` to `$_SERVER` and `$_ENV`?

**Comment by benja-M-1** [comment]
My suggestion is just dumb as the `Dotenv` class can only read `.env` format files... and not PHP files

**Comment by nicolas-grekas** [comment]
Fix in #571

**Comment by DanielRuf** [comment]
> Hum, yes, that's a limitation of using the compiled
> .env file.
> My recommendation is to not use `getenv()`:

So what is the solution in this case then? Use `$_ENV`?

**Comment by AkashicSeer** [comment]
Yeah thanks for recommending to not use getenv any suggestions as to what to do instead of using getenv? I am having a hell of a time getting symfony working due to not being able to figure out how to access environmental variables

**Comment by nicolas-grekas** [comment]
Check https://symfony.com/doc/current/configuration.html#configuration-based-on-environment-variables

**Comment by fmonts** [comment]
Sometimes other packages use `getenv`, for example google/auth, [here](https://github.com/googleapis/google-auth-library-php/blob/45a22aa/src/CredentialsLoader.php#L73).  
I use it for the [google/cloud-translate](https://packagist.org/packages/google/cloud-translate) service and after some debugging on why I was getting `Could not construct ApplicationDefaultCredentials` I arrived here... Any workaround?
