### ISSUE TITLE
Confusing default bootstrapping for "test" env

### ISSUE THREAD

**Issue by phansys** [symfony/recipes#574]
Given the changes made at #491, using [`config/bootstrap.php`](https://github.com/symfony/recipes/blob/c466e7a6cfa12b61a8e73537df518b4008a8f1c7/symfony/framework-bundle/3.3/config/bootstrap.php#L9) as bootstrap of phpunit is not possible if `.env.local.php` exists without variables that closely belongs to the "test" env ("KERNEL_CLASS", "SYMFONY_DEPRECATIONS_HELPER", etc); since the file from where these variables should be loaded (`.env.test`) isn't required at all:

https://github.com/symfony/recipes/blob/c466e7a6cfa12b61a8e73537df518b4008a8f1c7/symfony/phpunit-bridge/3.3/.env.test#L2-L4

Since these variables are not common for the local environment, the dumped array at `.env.local.php` doesn't contains them, making the test suite unusable without changes:

https://github.com/symfony/recipes/blob/c466e7a6cfa12b61a8e73537df518b4008a8f1c7/symfony/framework-bundle/3.3/config/bootstrap.php#L9-L13

**Comment by nicolas-grekas** [comment]
Yes, that's correct. We need to enhance documentation around this as it's quite new.
As you spotted, .env.local.php freezes .envelope files. As such and on purpose, it's only for prod-like needs. Don't use it in test nor dev.
