### ISSUE TITLE
[symfony/phpunit-bridge] bin/phpunit overwrites SYMFONY_PHPUNIT_VERSION

### ISSUE THREAD

**Issue by IonBazan** [symfony/recipes#577]
Running `bin/phpunit` ignores following environment variables set in `phpunit.xml.dist` and `.env.test` files:

- `SYMFONY_PHPUNIT_VERSION`
- `SYMFONY_PHPUNIT_REMOVE`

This is related to #476, has been fixed by #481 but came back after #491.

Steps to reproduce: 
Add the following line:
```xml
<env name="SYMFONY_PHPUNIT_VERSION" value="7.5" />
```
in `phpunit.xml.dist`'s `<php>` section.
Running `vendor/bin/simple-phpunit` - executes PHPUnit 7.5 ✅ 
Running `bin/phpunit` - ignores the setting and executes PHPUnit 6.5 ⚠️ 

This is caused by following change: https://github.com/symfony/recipes/pull/491/files#diff-bbc808450c0f3f12f5cec14fc21afc94R9

**Comment by nicolas-grekas** [comment]
Hello, this is expected: phpunit needs to be installed to read the XML file. And for it to be installed, it's version must be defined before... installing it.

**Comment by nicolas-grekas** [comment]
To configure the version that should be used, edit bin/phpunit

**Comment by IonBazan** [comment]
@nicolas-grekas Actually, the XML is parsed in `simple-phpunit` file before installing PHPUnit itself: https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/PhpUnit/bin/simple-phpunit#L40
Maybe it is not necessary to set this variable in `bin/phpunit` file at all?

**Comment by nicolas-grekas** [comment]
OH, then the change in #561 is what might have broken this.
Would you mind sending a PR to https://github.com/symfony/symfony/ against branch 4.2 to tweak the xpath for the new situation (while keeping compat with the old one)

**Comment by IonBazan** [comment]
I think #561 is not really the root of the problem, since using `server` instead of `env` does not help. The problem is that environment variables are fetched using `getenv()` in `bin/phpunit` but `vendor/bin/simple-phpunit` uses a fancy function which performs a lookup in environment variables and `xml` files: https://github.com/symfony/symfony/blob/7e56ef1a3deb722870d127d88d1383c63b85c10b/src/Symfony/Bridge/PhpUnit/bin/simple-phpunit#L18

Maybe we should make `bin/phpunit` simply require the `vendor/bin/simple-phpunit` and let it resolve all the environment variables.
