### ISSUE TITLE
[FrameworkBundle] Error 500 when installing Symfony Skeleton project

### ISSUE THREAD

**Issue by jls-esokia** [symfony/recipes#623]
**Symfony version(s) affected:** master

**Description**  

When installing symfony/website-skeleton, everything works out of the box.  But when installing symfony/skeleton, there is an error 500 because symfony/debug isn't install but is required in public/index.php

**How to reproduce**  

- `composer create-project symfony/skeleton test`

**Comment by Tobion** [comment]
See https://github.com/symfony/skeleton/pull/177
