### ISSUE TITLE
[RFC] Always put a reference configuration file for each recipe

### ISSUE THREAD

**Issue by maidmaid** [symfony/recipes#63]
My idea is to have for each recipe a commented reference configuration (in addition to uncommented minimal usefull config). In this way, we don't need to create config file and to search in options documentation: everything is here, under our eyes. It's verbose but this is no longer a problem now that each config has his own file. For example, ``debug`` recipe has actually no config file; would not it be useful to have for him a reference config file at the beginning of our projects, like this:

```yaml
#debug:

    # Max number of displayed items past the first level, -1 means no limit
    #max_items:            2500

    # Max length of displayed strings, -1 means no limit
    #max_string_length:    -1

    # A stream URL where dumps should be written to
    #dump_destination:     null # Example: php://stderr
```

**Comment by Pierstoval** [comment]
This is something you can have by running `bin/console config:dump-reference debug` actually, so "useful default values" is nice, but "all default values" maybe too overkill.

And actually, many current recipe are already bringing their own config file with commented values with explanations

**Comment by stof** [comment]
-1 for showing the full configuration. Bundles are meant to provide a good default when they can, meaning that most users may never need to configure things themselves. In this case, giving a commented reference adds content to what the user sees without any benefit.
Thus, if a new release of the bundle alters the default to a better value (or the default value is dynamic based on some condition), the commented value may not even be the default one.

**Comment by maidmaid** [comment]
> This is something you can have by running bin/console config:dump-reference {extension_name}

Yes, but do not forget that ``symfony/console`` (required for running this command) is not in skeleton.

**Comment by stof** [comment]
@maidmaid config files which are added inside the project by the recipe are not a replacement for the bundle documentation. so people not having the console can still go reading your doc.

**Comment by maidmaid** [comment]
> config files [...] are not a replacement for the bundle documentation

Of course! But if these recipes can we avoid a few trips to the external documentation, so why not.

**Comment by maidmaid** [comment]
Yes, have full config is maybe too overkill. What about to have just a *empty* config file with primary config key and a link to documentation, like this:

```yaml
# see https://symfony.com/doc/current/reference/configuration/debug.html
#debug:
```

**Comment by Pierstoval** [comment]
Empty and commented key is useless and has no real value for the project.

Documentation link is nice, but I think it has been decided by the Flex team that if the user installs a package, he/she should already be aware of where to find the documentation. Even though, I think a documentation link is good, but not sure about "where to put it". If the config file is empty, a config file with simply a link is really too much to carry IMO 😕

**Comment by stof** [comment]
The main drawback of using the config file for that is that you would get the file from the recipe corresponding to the time you initially installed the bundle. But if you update the bundle later, the commented settings you have in your file may not be the available ones anymore.

**Comment by fabpot** [comment]
Closing now as I think the current way is the best way.
