### ISSUE TITLE
Default assets:install command keeps getting readded to auto-scripts if using --relative --symlink

### ISSUE THREAD

**Issue by emodric** [symfony/recipes#631]
In our projects, we change `assets:install` command to install assets with relative symlinks.

However, when running `composer install` without `symfony.lock` and `composer.lock` present, the original version of the command from the recipe which uses hard copies gets re-added to the end of `auto-scripts` causing our assets to be installed with hard copies.

Is there any sane way to prevent this from happening?

Thanks!

**Comment by B-Galati** [comment]
Why are you missing the `symfony.lock` file? This file is required or you will have recipes reinstalled all the time.

**Comment by maxhelias** [comment]
`.lock` files are just there to prevent this case. Commit them and problem solved

**Comment by emodric** [comment]
I am aware of `symfony.lock` file purpose, yes :)

However, our usecase is a bit different. We have a blueprint installation from which all our other projects are instantiated. In that blueprint installation we don't keep lock files in order for new projects to always have latest versions of dependencies and recipes. It does however have `assets:install` command modified to include `--symlink --relative` because that's what we use in our setup exclusively.

This poses a problem for an initial project install (when instantiating from the blueprint) where the issue described happens.

**Comment by B-Galati** [comment]
Perhaps you could commit a minimal `symfony.lock` that would contain the package that modifies that line.

**Comment by emodric** [comment]
That is an option, yes, but not an ideal one. I also thought about it, but as we would still want to get latest versions of other recipe files, we haven't implemented it yet. That's why I asked is there maybe a saner way to handle this.

Thanks for the suggestions nevertheless, they are much appreciated :+1:

**Comment by nicolas-grekas** [comment]
Closing as the solution described by @[B-Galati](https://github.com/B-Galati) makes sense to me, and this stalled.
