### ISSUE TITLE
MonologBundle: excluded_http_codes breaks on pinned symfony 3.4

### ISSUE THREAD

**Issue by c33s** [symfony/recipes#639]
@weaverryan the PR #604 breaks 3.4 symfony installation. 

i assume its because symfony components are locked on `3.4` which should be ok for a LTS.
`composer.yaml`
```
...
extra:
    symfony:
        require: '3.4.*'
...
```

`symfony/monolog-bundle v3.4.0` -> `symfony/monolog-bridge: ~3.4|~4.0` leads to the installation of `symfony/monolog-bridge v3.4.30` which does not have the required handler.

this leads to:

```
  [LogicException]
  "excluded_http_codes" cannot be used as your version of Monolog bridge does not support it.
```

as this is a LTS version this really should not be so. i would suggest to remove this setting from the `3.3` receipe and move this setting to a `4.x` version of `symfony/monolog-bridge`

**Comment by ianfoulds** [comment]
Can someone address this problem please, it is breaking my Travis CI testing when calling self::bootKernel().

**Comment by nicolas-grekas** [comment]
There is nothing we can do here, it's something that should be resolved on the composer.json side of things.

@ianef recipes should not be installed on the CI...
