### ISSUE TITLE
[Doctrine] DATABASE_URL instead of separate DATABASE_* variables less usable

### ISSUE THREAD

**Issue by dkarlovi** [symfony/recipes#64]
Obviously, having a [single database configuration string](https://github.com/symfony/recipes/blob/master/doctrine/doctrine-bundle/1.6/etc/packages/doctrine.yaml#L3) is much easier for Flex, but makes it harder / more awkward to reuse the environment variables for other purposes, say [injecting them to a MySQL Docker container](https://github.com/dkarlovi/symfony-flex-docker/blob/master/docker-compose.yaml#L24-L28) as the required values are embedded inside a Doctrine-specific connection format.

Obviously, I can [ship my own database config](https://github.com/symfony/recipes-contrib/pull/15/files#diff-26c5d473a65029a58bbe9a756d3e0b42) which gets the job done, but it means the user will have to specify database settings in .env twice which will get confusing.

**Comment by javiereguiluz** [comment]
The database URL seems to be the format recommended by Doctrine (http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html) and if I'm right, it's also common in SaaS/PaaS services.

Can't Docker use this syntax in any way? Thanks!

**Comment by dkarlovi** [comment]
@javiereguiluz,

I don't see how, to be honest. Docker is not doing anything special here, it's just injecting the pre-existing environment variables, it's depends on the Docker image in which format it expects it. As this uses the [official MySQL Docker image](https://hub.docker.com/_/mysql/), the environment variables (and their semantics) are predefined. It's recommended to use the official Docker images as base images for your projects.

I agree PaaS are using a bulk connection string as that makes using the service easier, but this is a special case in which you wish to supply the same information to two different entities: MySQL Docker image for it to set itself up, Symfony app for it to connect to the set-up image. It would be best if you could specify the same config only once.

I can work around this by constructing the `DATABASE_URL` environment variable for app container (the same way I'm renaming `DATABASE_*` variables to `MYSQL_*` variables, linked above) and explain to the user to just delete `DATABASE_URL` from their `.env`), but that's the "awkward" part of this issue: it can't be done automagically.

Just opened this issue to confirm this is a known side effect and Flex is fine with it (as it might be considered a corner case).

**Comment by stof** [comment]
@dkarlovi you don't even need to make them delete it from the .env, as a real env variable being set wins over the .env file.

And for your docker container, you could indeed build the env variable from other env variables if you have a need to reuse the same credentials in multiple containers. Doing it this way should be easy (probably a one-liner in the Dockerfile), while making flex expect separate env variables rather than a URL would be a pain for PaaS deployments (people would have to write a script parsing the URL and reinjecting individual parts as env variables)

**Comment by dkarlovi** [comment]
@stof this doesn't use Dotenv component, it's Docker Compose-based which will set all the variables from .env. I depends on what it's doing which variable will "win", need to test it out.

The problem here is that the users will end up with both DATABASE_URL (from Doctrine Bundle) and my DATABASE_* variables in .env, they'll need to know DATABASE_URL will be overwritten (ignored) by Docker Compose, that's the reason why it's probably better to instruct them to delete it.

Workaround for this:
1. user installs Doctrine Bundle (which adds DATABASE_URL)
2. user installs my Docker package (which adds single DATABASE_* variables and builds DATABASE_URL as expected by Doctrine Bundle)
3. user needs to delete DATABASE_URL from their .env as it's not used and will get confusing why there are two of them

> people would have to write a script parsing the URL and reinjecting individual parts as env variables

That's exactly why I'm saying DATABASE_URL is harder to use than individual DATABASE_* vars in this scenario, don't understand your point here. DATABASE_URL requires parsing, not the individual DATABASE_* vars, not the other way around.

**Comment by stof** [comment]
@dkarlovi DATABASE_URL does not require project-level parsing on PaaS if this is what your project expects (as you already have what you expect). It will of course be parsed inside the Doctrine DBAL layer, but this is internal.
If you code your project to expect separate env variables and you deploy to a PaaS, you need to write custom glue code altering the env before booting your app, to extract the separate env vars from the URL the PaaS gives you.

**Comment by Pierstoval** [comment]
I personally moved an app from a dedicated server to Heroku, and migrated lots of parameters to env vars, especially database credentials. As I'm using 2 different databases (SF app & legacy connection), having 10 env vars to setup is totally useless when I can have only 2 env vars corresponding to database urls.

I think docker players should handle URLs, as like @stof says, PaaS uses this A LOT to simplify apps configuration

**Comment by dkarlovi** [comment]
@stof 

> DATABASE_URL does not require project-level parsing on PaaS if this is what your project expects

DATABASE_URL syntax is proscribed by Doctrine, not by specific PaaS vendors. I'd be surprised if all (or even most relevant) PaaS vendors offered a Doctrine-specific connection string which you can just use as-is.

You'll need to "translate" their connection string to whatever format your app expects anyway, be it DATABASE_URL or DATABASE_* The parsing in this case is done by the developer / ops.

> If you code your project to expect separate env variables and you deploy to a PaaS, you need to write custom glue code altering the env before booting your app

You don't write any glue code, you supply the connection information in a way your app expects (environment variables). The difference here is only that DATABASE_URL encapsulates multiple variables in a proprietary format while separate DATABASE_* variables don't, each variable has exactly one (known) semantic.

My setup (linked repo) allows for you to build your images once and run them (the exact same images) in whatever environment and/or runtime you desire, that's the whole point.

BTW just realized this: [supplying secrets via env variables](http://movingfast.io/articles/environment-variables-considered-harmful/) is [being deprecated](https://kubernetes.io/docs/concepts/configuration/secret/), it will be hard to support this by having the entire connection string in bulk. Obviously, Symfony first needs to support reading stuff and injecting to DI from files.

**Comment by stof** [comment]
@dkarlovi the convention is not specific to Doctrine. Actually, doctrine borrowed it from Rails precisely to be compatible with the way several PaaS expose the DB credentials.

**Comment by stof** [comment]
And on PaaS, you don't provide the DB URL. *They* provide it. So it your app wants separate variables while they give you a URL **you** have to write glue code converting the provided env variable to multiple ones (and you should keep using env variables in Symfony itself, because otherwise your credentials gets cached and you have to clear the cache when they change the credentials, which is precisely what made it more painful to deploy on Heroku & co before 3.2)

**Comment by dkarlovi** [comment]
This might be quite Heroku-specific, I'm currently looking at Azure and AWS and they both do not provide a Doctrine-compatible connection string. They tell you the values to use, it's up to you to supply them to your app.

**Comment by dkarlovi** [comment]
I think I understand your arguments now @stof: you're thinking of a **really** specific use-case in which your application is almost an appliance, it gets run by the underlying platform in a very specific way, as in Heroku (Azure also has a limited runtime like this, I think they call it "web apps"). I agree this solution is much superior if using Heroku or such appliance environment.

I'm thinking about running apps not on Heroku, but containerized on Openshift or Kubernetes, which are suitable target platforms for Docker apps. You supply Docker images (say, via a private Docker registry) and a "recipe" in which your app is supposed to be run (support for building such recipes will also be part of my repo). You could then run the DB as a container or register a PaaS database from your cloud provider in your Openshift instance, your app doesn't care, it just connects to whatever you tell it to.

**Comment by dkarlovi** [comment]
You don't only clear the cache if changing the database host / config: as it's a config change, you deploy a whole new container set.

**Comment by teohhanhui** [comment]
For Docker, just use an `ENTRYPOINT` script.

**Comment by dkarlovi** [comment]
@teohhanhui you mean, in the database image?

Yeah, that would work and is probably the only place to parse the DSN (again, we're parsing a proprietary string instead of only injecting values), but now you need to write and bundle a custom init script for each DB service. It's not difficult, but it's only necessary because of this change.

Also, it doesn't solve the problem of [secrets in environment variables being an anti-pattern](http://movingfast.io/articles/environment-variables-considered-harmful/), linked before.

**Comment by stof** [comment]
Reading secrets from the filesystem at runtime requires creating new features in Symfony to support that first. currently, it is not supported.

**Comment by dkarlovi** [comment]
@stof obviously. That doesn't mean it's not an anti-pattern.

**Comment by stof** [comment]
@dkarlovi yeah, but keeping mentioning this in this discussion is useless: recipes have to use working features. For now, using env variables is an option. Using the new docker-only way of reading secret from special files is not.

**Comment by teohhanhui** [comment]
@dkarlovi No, not in the database image, but in the app image. It makes sense to do it, because it's a "Symfony app" image.

**Comment by dkarlovi** [comment]
@stof 

> recipes have to use working features

Of course, agreed.

I keep bringing the topic up because it might not be obvious right away, and slapping all the connection settings into a single string **moves the target away** from the (hopefully?) desired outcome: **having secrets injected in a secure way** (because you can switch the password to be read from the file-system easily, not if you use a DSN).

With this recipe staying as-is, having secrets embedded in DSN is the Symfony-recommended way which will need to be undone at some point when the more secure "secrets from files" feature is added.

> new docker-only way 

Having secrets in env is not bad only on Docker, don't see your point here.

@teohhanhui don't really understand you here, mind giving an example? Database settings are already in a Symfony-compatible format, don't need to change anything there. Related services are the problem here.

**Comment by teohhanhui** [comment]
`docker/app/Dockerfile`:
```Dockerfile
...

COPY docker/app/docker-entrypoint.sh /usr/local/bin/docker-app-entrypoint
RUN chmod +x /usr/local/bin/docker-app-entrypoint

ENTRYPOINT ["docker-app-entrypoint"]
CMD ["php-fpm"]
```

`docker/app/docker-entrypoint.sh`:
```sh
#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

if [ "$1" = 'php-fpm' ]; then
	export DATABASE_URL
	DATABASE_URL="pgsql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DBNAME}?charset=UTF8&serverVersion=9.6"
fi

exec docker-php-entrypoint "$@"
```

**Comment by stof** [comment]
@dkarlovi AFAIK, all PaaS out there rely on env variables, not on docker-style secrets

**Comment by dkarlovi** [comment]
@stof again: you've said that before and I've checked in AWS and Azure: you don't get a pre-configured appliance-like environment DATABASE_URL there if you're using their PaaS databases, you just get settings to inject into your app in which ever way you want (be it env, be it parameters.yml, be it filesystem secrets). Also again, this is not "Docker-style" as it's common to setup secrets in files with usual provisioning tools such as Ansible, Chef, Puppet - no Docker there.

@teohhanhui you have me confused here: **there're no DB_* variables** to concatenate into a DATABASE_URL env variable to begin with, that's the whole point of this issue. :)

**Comment by teohhanhui** [comment]
So, `DATABASE_URL` is used by the (Symfony Flex) project. There is nothing
stopping you as the author of your own Docker Compose setup to pass
whatever other environment variables to your app container, and doing any
necessary processing from there.

**Comment by dkarlovi** [comment]
@teohhanhui of course, that's what I'm already doing in my package. The problem is, the user will end up with both DATABASE_URL and separate DATABASE_* variables in the `.env` file, but DATABASE_URL will be ignored. It's all described previously in this issue.

**Comment by teohhanhui** [comment]
There is no reason to use Symfony's `.env` when using Docker. If you are
referring to the Docker equivalent (`--env-file` / `env_file`), then
there's no reason to have `DATABASE_URL` in it, because it should only be
exported by the `ENTRYPOINT` script at runtime.

**Comment by dkarlovi** [comment]
@teohhanhui gist of this issue:

1. recipe for Doctrine bundle [uses DATABASE_URL](https://github.com/symfony/recipes/blob/master/doctrine/doctrine-bundle/1.6/etc/packages/doctrine.yaml#L3) instead of separate DATABASE_* variables used before
2. it also creates [an entry in `.env`](https://github.com/symfony/recipes/blob/master/doctrine/doctrine-bundle/1.6/manifest.json#L13) with that variable
3. this "looks better" and has some synergy with Heroku, but makes re-using those values awkward / harder,  as they're embedded into a proprietary string instead of being stand-alone, you need to parse them out. So, it's a trade-off: Heroku integration ++, Docker integration --, I guess it's a matter of priorities.
4. as an extra, it makes removing secrets from your environment harder long-term (once Symfony gets support for reading secrets from filesystem), which is MUCH better security-wise
5. If I install my package, it will re-add those separate DATABASE_* variables, but the problem is, the user will end up with both DATABASE_URL and DATABASE_* variables in his/her `.env` file (which will be confusing), I'd like to re-use existing variables, not rewrite them (and confuse the user in the process)

So, there are two solutions if this remains as-is (which seems likely):

1. add an custom `ENTRYPOINT` which will parse the DSN inside the database image, this is not great as any DB image needs it. Upside: it's probably not complex.
2. just add my separate DATABASE_* variables and advise the user to delete DATABASE_URL from their `.env`, also not great, but probably better than 1.

Closing.

**Comment by teohhanhui** [comment]
@dkarlovi I'm not sure what else I can provide to help you understand my approach. I've tried...

**Comment by dkarlovi** [comment]
I understood your explanation perfectly as I'm already doing (almost) exactly that, but it's not a solution to the original problem: DATABASE_URL is not usable in this use-case where you need to send DB username, password and name to two separate subsystems, both of which expect it in different formats.

**Comment by teohhanhui** [comment]
No, I do not set `DATABASE_URL` in the environment variables of any Docker container. It's only assembled by the `ENTRYPOINT` script in the (Symfony) `app` image. I only need to provide the separate components including `DB_HOST`, `DB_PORT`, `DB_USER`, `DB_PASSWORD` and `DB_DBNAME`.

Unless you are talking about incompatible formats of the `DATABASE_URL` as a part of your Symfony app (e.g. from a different package), in which case we've been talking about different things all along, and I apologize... p/s: Lack of standardization is a real issue. The URL format that Doctrine uses is not even the same as what PHP PDO uses as DSN.

**Comment by teohhanhui** [comment]
Uhh, I've just checked out your link in the OP, and I understand what you're saying now. And that's exactly a demonstration of why I'm against Symfony Flex generating any kind of Docker / Docker Compose setup.

**Comment by dkarlovi** [comment]
It does make some sense as you'd want to use specific Docker setup with certain bundles.

For example, it would be easy to attach Varnish to FOSHttpCacheBundle or RabbitMQ to Enqueue Bundle, I'd expect Flex to provide configuration for the bundles and some other package to figure out the Docker integration part.

Sadly, as it stands, Symfony folks are quite rigid with the direction Flex is taking which might hinder these kinds of more advanced integrations, hopefully it changes as the tool matures.
