### ISSUE TITLE
Change some permissions in the default front controller?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/recipes#650]
We received this report in Symfony Docs: https://github.com/symfony/symfony-docs/pull/11592/files

What do you think? Should we make any change in the default `index.php`? https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/4.4/public/index.php

**Comment by nicolas-grekas** [comment]
Does this happen when using Symfony Cache, or only when using Doctrine Cache?

**Comment by Deamon** [comment]
Hi @nicolas-grekas, we have the problem with the Doctrine Cache

**Comment by stof** [comment]
Well, the best solution is not to change the umask (that is the poor man solution).

A Doctrine query result cache is indeed a cache that cannot be warmed up fully, and so will have writes happening for web requests. If you use the filesystem to store such cache, you still need to make sure your setup supports writing for both the CLI and the webserver. ACLs are a better solution for that than umask.

I think we might need to resurrect the doc page about setting up ACLs, for cases needing this (improvements in the cache warmup of Symfony made this less needed than before, but it depends on what other caches you have).
Note that another solution is to avoid using the filesystem for the query result cache...

**Comment by javiereguiluz** [comment]
I'm closing this old issue ... in the Symfony Docs repo there are some issues about this permission article, so the Doc Team will take it from here. Thanks!
