### ISSUE TITLE
symfony 4.3.8 unable to install doctrine-orm using flex

### ISSUE THREAD

**Issue by lijunhaoabroad** [symfony/recipes#680]
composer require orm

it shows an error: [UnexpectedValueException]
  Invalid version string ""

<img width="557" alt="Screen Shot 2019-11-17 at 20 51 51" src="https://user-images.githubusercontent.com/15603606/69013048-1a4bee80-097c-11ea-852d-06578691b534.png">

**Comment by nicolas-grekas** [comment]
see https://github.com/symfony/flex/issues/571
