### ISSUE TITLE
[TwigBundle] Missing configuration for Symfony 5

### ISSUE THREAD

**Issue by HypeMC** [symfony/recipes#685]
The configuration yaml for the twig bundle for symfony 5 [seems to have been deleted](https://github.com/symfony/recipes/commit/822d42641360481779bb248d6362f072272436c9).
Not sure whether this was intentional, but it looks like a bug to me.

**Comment by xabbuh** [comment]
Isn't the latest available recipe version used then?

**Comment by nicolas-grekas** [comment]
As the linked commit shows, the file has been deleted and replaced by a new one in framework bundle.
You should do the same in your app.
We'd need an UPGRADE note about this in symfony/symfony

**Comment by HypeMC** [comment]
@xabbuh No, I did a clean Symfony 5 install with `composer create-project symfony/website-skeleton symfony5 5.0.*` & there's no `twig.yaml` present.

@nicolas-grekas As far as I can tell the PR is about replacing the route for the error page with the one in the framework bundle, has nothing to do with the configuration.

**Comment by xabbuh** [comment]
@HypeMC Indeed, I missed that there are still other files in the `5.0` directory. I though the whole directory didn't exist now.

**Comment by yceruto** [comment]
That was a mistake, restoring the configuration here https://github.com/symfony/recipes/pull/686
