### ISSUE TITLE
Doctrine migrations does not aknowlege changes in entities

### ISSUE THREAD

**Issue by liorchamla** [symfony/recipes#688]
It seems that since this PR (https://github.com/symfony/recipes/pull/682/commits/bf7c5fd70a828a6e0a3be2f8f9e968883c0c7b8e ) the `make:migration` command is "bugged".

It does not take into accounts changes made to entities and just generate the minimum SQL to create the tables and add an id.

By now, we have to run `doctrine:cache:clear-metadata` each time we change an entity if we want `make:migration` to take changes into account.

To be honest I absolutely don't know what happened and how I can fix it, so please apologize for not being able to create a PR.

**Easy to reproduce** : create a new Symfony app using `composer create-project symfony/website-skeleton demo` then create a first entity and run `make:migration` then look at the migration file. You will see that it only creates the table. If you want it to take into account all fields metadata, you will had to run `doctrine:cache:clear-metadata` and then `make:migration` will be fine :)

**Comment by dsentker** [comment]
I have the same problem. This seems like a bug, a very annoying one. Any ideas for this?

**Comment by dmaicher** [comment]
Yes this is currently an issue with wrongly configured caches on DoctrineBundle. We are working on a fix.

See https://github.com/doctrine/DoctrineBundle/pull/1073

**Comment by nobsod-freelance** [comment]
In the same way, there is a problem when you create a **OneToOne** relation with cascade persist : it doesn't persist the associated entity. You have to run `doctrine:cache:clear-metadata` as said by @liorchamla above.

**Comment by dmaicher** [comment]
There are new patch releases on DoctrineBundle to address this issue.

Please also make sure to sync the latest recipe changes seen here to ensure proper caching in prod: https://github.com/symfony/recipes/pull/695/files
