### ISSUE TITLE
Hardcoded PHPUnit version and different PHP versions

### ISSUE THREAD

**Issue by xabbuh** [symfony/recipes#701]
In #637 we bumped the PHPUnit version that will be installed when running `simple-phpunit` from 6.5 to 7.5. In most cases this is fine. However, when using an older PHP version (e.g. 7.0) you will end up with a PHPUnit version that is not compatible (see for example symfony/symfony#34809).

What do we do here? Making that value dynamic based on the PHP runtime version is not (easily) possible if I am not mistaken. Do we ignore this as PHP 7.0 is EOL for a long time? Should we add a warning (not sure if anyone will read it while installing the package)?

**Comment by stof** [comment]
I'm wondering whether we should hardcode a PHPUnit version at all, or let the bridge perform its version guessing.

**Comment by GinoPane** [comment]
We use PHP 7.4 and the PHPUnit version from the bridge is too old (though supported) because we have version 9 already. I think better versioning is required here.

**Comment by nicolas-grekas** [comment]
About older versions, the more we wait the less relevant the issue is.
But this means we shouldn't but to phpunit versions that don't support the lowest php version of the installed Symfony base.
@GinoPane upgrading to newer versions is your responsibility - this file is yours once installed.
