### ISSUE TITLE
[Bug] Do not use @ in recipe as it introduce some silent errors which prevent prper xdebug.

### ISSUE THREAD

**Issue by Yivan** [symfony/recipes#717]
Hello,

In this recipe https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/4.2/config/bootstrap.php#L9, using @include make xdebug throw an error and stop at this line each time runned.

Please see an example here:

![image](https://user-images.githubusercontent.com/9025839/71673323-c43ed900-2d78-11ea-85a0-315b04e41c9d.png)

You can have more details if needed here:
https://github.com/pimcore/pimcore/issues/5484#issuecomment-570215955

It is more proper to test file existance i think.

Thanks!

**Comment by nicolas-grekas** [comment]
This is on purpose, you should disable `xdebug.scream` mode in your php ini settings.

**Comment by Yivan** [comment]
@nicolas-grekas Thanks for looking into it.
I was not aware of this option.
For those interrested, I found information here https://xdebug.org/docs/all_settings

```
boolean xdebug.scream = false
Introduced in Xdebug >= 2.1

If this setting is 1, then Xdebug will disable the @ (shut-up) operator so that notices, warnings and errors are no longer hidden.
```

**But it is already disabled in my case**, please see:

![image](https://user-images.githubusercontent.com/9025839/71684122-e181a080-2d94-11ea-94cd-4f176a290f54.png)

And VSCode is configured with:

![image](https://user-images.githubusercontent.com/9025839/71684442-cc594180-2d95-11ea-82f3-e2a086d66acc.png)

As it is an exception which is raised, it prevent to use JIT feature of xdebug, as any request will be catched during bootstrap and the step need to be passed manually...

**Comment by nicolas-grekas** [comment]
> But it is already disabled in my case

OK, then this is maybe an issue with VScode ignoring the `@` operator?
This operator means any error should be silenced. If it's not the case, the issue is not in the code but in the thing that reports the error.

**Comment by Yivan** [comment]
Thanks, yes maybe it is vscode fault. But I am not sure as the debug extension should only say what xdebug report... I have not other IDE to test. If any people here can give their experience on it please.

Anyway I opened an issue on the php debug extension of vscode: https://github.com/felixfbecker/vscode-php-debug/issues/385

In all case, it would be proper to test file existence instead using @ operator I really think, because this is a central file for boostraping so should be clean without the @ hack so bootstraping work seamless with any tools and never report any errors (debug tools, displayed or log files).

A fix like this is easy to add to the symfony recipe: https://github.com/pimcore/pimcore/commit/7887c7c5c2d0706b07bad175076201be5fbdaaff

Thanks.

**Comment by nicolas-grekas** [comment]
We rejected using file_exists() before because it creates i/o, which we'd better avoid on the hot path when we can, especially for working around broken tools.

**Comment by Yivan** [comment]
I understand this choice, thanks for explaination.
Feel free to close this issue if you think this is to vscode/extension to handle this, or you can leave it pending waiting for vscode answer.
Thanks again.
