### ISSUE TITLE
move doctrine migrations away from src

### ISSUE THREAD

**Issue by ro0NL** [symfony/recipes#718]
it was briefly discussed here https://github.com/symfony/recipes/pull/172#issuecomment-328376549, but seems to be ignored eventually

i like to propose to move `src/Migrations` to `migrations/`. I dont understand why we are moving mountains to keep it in src (extra config etc.)  :/ is there any technical blocker to not move it away from src?

semantically it does not belong in src IMHO.

(https://www.tomasvotruba.cz/blog/2019/12/23/5-things-i-improve-when-i-get-to-new-repository/#3-move-code-to-src)

**Comment by ogizanagi** [comment]
I'm already doing this for all of my projects. So 👍 from me.

**Comment by ro0NL** [comment]
alternatively to introduce a more generic/reusable directory in our landscape: `./scripts/database-migrations/`? But im not sure it's valid UNIX style let's say.

We should carefully think about root directories though, at some point it gets out of control.

**Comment by ogizanagi** [comment]
The more generic/reusable proposition [was made a long-time ago](https://github.com/symfony/recipes/pull/253#issuecomment-345467929), but without enough traction/consensus to happen: a `res` directory which would contains any resources / non "runtime" source code of the application, i.e:

- migrations
- assets
- fixtures
- templates
- docs
- translations
- ...

**Comment by ro0NL** [comment]
:heart_eyes: can we do that? please? :grin:

**Comment by yceruto** [comment]
I like `migrations/` at the root too :+1:

**Comment by ro0NL** [comment]
@javiereguiluz ive reread the issue real quick, fair enough :) the ship has sailed. I still think it's more concise in general, but :+1: for many root dirs tied to SF, in a SF specific project dir.

**Comment by dmaicher** [comment]
Also related discussion: https://github.com/doctrine/DoctrineMigrationsBundle/pull/295/files#r362401350
