### ISSUE TITLE
"Force" option when reinstalling a recipe does not force if same version already installed

### ISSUE THREAD

**Issue by pmishev** [symfony/recipes#745]
Let's say I edit or delete my bin/phpunit file and I want to recover it by executing the phpunit-bridge recipe.

I run `composer recipes:install symfony/phpunit-bridge --force -v` expecting it to recreate the file, however nothing happens.

If I want to ***actually*** force this, I need to edit symfony.lock and remove the recipe.ref value of "symfony/phpunit-bridge", before running the above command.

**Comment by nicolas-grekas** [comment]
Since https://github.com/symfony/flex/pull/795 you can use `composer recipes:install --force --reset`
