### ISSUE TITLE
[symfony/monolog-bundle] in prod env console handler maybe not available

### ISSUE THREAD

**Issue by ttskch** [symfony/recipes#752]
[prod/monolog.yaml uses console handler](https://github.com/symfony/recipes/blob/2de05e19f916c8841102f2a35f0dc08dbac219ed/symfony/monolog-bundle/3.3/config/packages/prod/monolog.yaml#L14) and the `ConsoleHandler` class [depends on symfony/console](https://github.com/symfony/monolog-bridge/blob/fd9750c732596742ee4f890a0a236881aad26c11/Handler/ConsoleHandler.php#L19-L23).

But [symfony/monolog-bundle depends on symfony/console **only as "require-dev"**](https://github.com/symfony/monolog-bundle/blob/72e798ccdcfd277a6bc88e934b43f618732e3561/composer.json#L28).

So in following situation "class not found error" will be occured🤔

* [symfony/monolog-bundle](https://github.com/symfony/monolog-bundle) and [recipe for it](https://github.com/symfony/recipes/tree/master/symfony/monolog-bundle) are installed
* `composer install --no-dev`
* `APP_ENV=prod`

```
PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Console\ConsoleEvents' not found in /path/to/vendor/symfony/monolog-bridge/Handler/ConsoleHandler.php:139
```

**Comment by Tobion** [comment]
I guess we could make symfony/monolog-bridge (which defines the ConsoleHanlder) require symfony/console.

**Comment by Tobion** [comment]
But why would you not have symfony/console? It's a default requirement of the skeleton: https://github.com/symfony/skeleton/blob/master/composer.json

**Comment by ttskch** [comment]
@Tobion 

> It's a default requirement of the skeleton:

Oh... I didn't know that because I always use [my own skeleton](https://github.com/ttskch/symfony-micro-skeleton) 😓I'm catching it up.

**Comment by stof** [comment]
For Flex, we decided that not having the console was too painful, as a Symfony project which does not have access to at least `cache:clear` and `cache:warmup` becomes painful to manage (we tried making the console optional in the skeleton in the early days of Flex).

**Comment by Tobion** [comment]
Closing as flex requires the console
