### ISSUE TITLE
Kernel.php not updated going from 5.0 to 5.1

### ISSUE THREAD

**Issue by evotodi** [symfony/recipes#779]
Changing the composer requirements from 5.0.* to 5.1.* and performing a composer update does not update the src/Kernel.php file. 
While the kernel still works it throws a depreciation warning about RouteCollectionBuilder.

To reproduce:
* Create a skeleton symfony 5.0 project with:
   ```
   symfony new --dir=./ --version=5.0 --no-git
   ```
* In composer.json replace all occurrences of 5.0.* with 5.1.*
* Run composer update

To work around:
* Replace the contents of Kernel.php with this [Kernel.php](https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/5.1/src/Kernel.php)

The fix:
I think the issue is that manifest.json is empty so therefor the kernel.php file is not updated.

**Comment by fabpot** [comment]
I think you are are looking for `composer sync-recipes --force`.

**Comment by maxhelias** [comment]
@evotodi You will have all the necessary information regarding recipes with this command: `composer recipes` 😉

**Comment by evotodi** [comment]
Thank you for the speedy replies.
Please excuse my ignorance but i find no mention of simplifying the Kernel.php in the 5.0 or 5.1 change log or features from here [5.0](https://symfony.com/releases/5.0) or here [5.1](https://symfony.com/releases/5.1) and causing a depreciation. 

Following the depreciation notice `Since symfony/framework-bundle 5.1: Using type "Symfony\Component\Routing\RouteCollectionBuilder" for argument 1 of method "App\Kernel:configureRoutes()" is deprecated, use "Symfony\Component\Routing\Loader\Configurator\RoutingConfigurator" instead.` recommendation of changing the use statement and type hint to RoutingConfigurator causes a 404 on all routes. 

Running `composer sync-recipes --force` does allow the update of Kernel.php among others so thank you for that.
