### ISSUE TITLE
SYMFONY_DEPRECATIONS_HELPER in .env.test not working

### ISSUE THREAD

**Issue by pdugas** [symfony/recipes#782]
I suspect I have something a little scrambled so bear with me please. I added `symfony/phpunit-bridge` to my current project a long time ago. I have not be re-applying recipes as dependencies were updated until recently. I find my CI build it failing now because deprecation errors cause phpunit to return a non-zero exit code. It seems something has changed and the ./bin/phpunit script generated by the recipe is no longer picking up the `.env.test` settings so `SYMFONY_DEPRECATIONS_HELPER=999999` isn't set.  If I manually set it and run `bin/phpunit`, I get the expected zero exit code.

Is something broken on my end or what?

**Comment by Tobion** [comment]
I'm sorry, but in the GitHub repository we only discuss about Symfony bugs and new features. For questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!

You need to make sure all the recipes like loading env vars are up-to-date. Not much we can do here without a reproducer.

**Comment by pdugas** [comment]
https://github.com/symfony/recipes/blob/e03825eb26106120bc280d90470c9cceadcb65b5/symfony/framework-bundle/4.2/config/bootstrap.php#L17

I think this line
```
(new Dotenv(false))->loadEnv(dirname(__DIR__).'/.env');
```
needs to become something like
```
(new Dotenv())->usePutenv(false)->loadEnv(dirname(__DIR__).'/.env');
```

Without that change, the `.env.test` file wasn't being loaded when running unit tests.

**Comment by pdugas** [comment]
That also resolves a deprecation warning about passing a bool to the Dotenv ctor.

**Comment by nicolas-grekas** [comment]
`(new Dotenv(false))->loadEnv(dirname(__DIR__).'/.env');`
should become
`(new Dotenv())->loadEnv(dirname(__DIR__).'/.env');`
