### ISSUE TITLE
Proposal for a new recipe validation rule

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/recipes#80]
In https://github.com/symfony/recipes-contrib/pull/39/files commented lines add the `#` at the beginning of the line.

In https://github.com/symfony/recipes-contrib/pull/22/files commented lines add the `#` at the beginning of the commented content.

Should we standardize this?

**Comment by sstok** [comment]
I think it's best use at the beginning of the line, it gives clarity, is easy to remove with a regex, and easy to type 😛

**Comment by fabpot** [comment]
I don't see any easy way to do that, so I'm closing for now.
