### ISSUE TITLE
Allow PHP config in packages/ and routes/ folders

### ISSUE THREAD

**Issue by ghost** [symfony/recipes#805]
[The current recipe for framework-bundle](https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/5.1/src/Kernel.php) does'nt take into account the .php configuration files in the `config/packages/` folder.

In the same way, it's configured to only receive routes from a single `routes.php` file in the `config/` folder, but it should be possible to have multiple .php files to configure routes inside the `config/routes/` folder.

Since the use of php file-based configuration will be promoted in future versions of Symfony, this feature should be possible from now on.

**Comment by TavoNiievez** [comment]
Working config...
```diff
class Kernel extends BaseKernel
{
    //...

    protected function configureContainer(ContainerConfigurator $container): void
    {
+        $container->import('../config/{packages}/*.php');
         $container->import('../config/{packages}/*.yaml');
+        $container->import('../config/{packages}/'.$this->environment.'/*.php');
         $container->import('../config/{packages}/'.$this->environment.'/*.yaml');

		//...
    }

    protected function configureRoutes(RoutingConfigurator $routes): void
    {
+        $routes->import('../config/{routes}/'.$this->environment.'/*.php');
         $routes->import('../config/{routes}/'.$this->environment.'/*.yaml');
+        $routes->import('../config/{routes}/*.php');
         $routes->import('../config/{routes}/*.yaml');

		//...
    }
}
```

**Comment by Tobion** [comment]
See https://github.com/symfony/recipes/pull/840#issuecomment-722363810 and https://github.com/symfony/recipes/pull/840#issuecomment-735235216
