### ISSUE TITLE
There are not recipies for Easy Admin 3, and the current one is not working

### ISSUE THREAD

**Issue by lyrixx** [symfony/recipes#827]
ping @javiereguiluz 

--- 

And the V2 is not compatible with SF5.1+

```
~/app/apps/api composer req easycorp/easyadmin-bundle:2
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.1.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for easycorp/easyadmin-bundle 2 -> satisfiable by easycorp/easyadmin-bundle[v2.0.0].
    - easycorp/easyadmin-bundle v2.0.0 requires doctrine/doctrine-bundle ^1.8 -> satisfiable by doctrine/doctrine-bundle[1.10.0, 1.10.1, 1.10.2, 1.10.3, 1.10.x-dev, 1.11.0, 1.11.1, 1.11.2, 1.11.x-dev, 1.12.0, 1.12.0-Beta1, 1.12.1, 1.12.10, 1.12.2, 1.12.3, 1.12.4, 1.12.5, 1.12.6, 1.12.7, 1.12.8, 1.12.9, 1.12.x-dev, 1.8.0, 1.8.1, 1.8.x-dev, 1.9.0, 1.9.1, 1.9.x-dev] but these conflict with your requirements or minimum-stability.


```

**Comment by javiereguiluz** [comment]
The fact that there's no recipe for EA3 should be correct. We don't need any config file (for routes or services or anything else).

For the EasyAdmin 2 compatibility, please open an issue (or a PR) in the https://github.com/EasyCorp/EasyAdminBundle repository so we can tackle it. Thanks!

**Comment by stof** [comment]
don't we need an empty recipe to cancel the EA2 recipe ?

**Comment by javiereguiluz** [comment]
I guess we didn't need it. Let's reopen this then to discuss about it.

**Comment by nicolas-grekas** [comment]
we do need an empty one :)

**Comment by javiereguiluz** [comment]
@nicolas-grekas thanks for confirming! In #828 I copy+paste the 2.0 recipe but removed all the copy file logic.

**Comment by stof** [comment]
btw, the recipe is not even empty, as we want to still want to register an alias.
