### ISSUE TITLE
Suggestion: Show recipe name in composer output

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/recipes#834]
After doing `composer update`, I'm getting:
```
Symfony operations: 1 recipe (20dfc4e46c7b7d0a930db3febc76557f)
  - Unconfiguring phpstan/extension-installer (>=1.0.5): From auto-generated recipe
phpstan/extension-installer: Package not found (probably scheduled for removal); extensions installation skipped.
```
... which tells me that *something* killed `phpstan/extension-installer`. But which recipe was it? So I'm suggesting to replace/augment the "20dfc4e46c7b7d0a930db3febc76557f" with the recipe's name/URL.

**Comment by BoShurik** [comment]
Can you show `composer why phpstan/extension-installer` output before `composer update`

**Comment by ThomasLandauer** [comment]
I installed it manually myself (see https://github.com/phpstan/extension-installer#usage), so I have it in `composer.json`s `require-dev`. Actually: I *had* it there, cause it's gone now ;-)

**Comment by nicolas-grekas** [comment]
A recipe is removed when the corresponding package is removed. But a recipe never "removes" a package. You must have done something to remove the package, unrelated to flex.

**Comment by BoShurik** [comment]
Maybe you ran `composer update --no-dev`?

**Comment by ThomasLandauer** [comment]
No, I just ran `composer update` - as always. And if I'd deleted it from `composer.json`, the output would be different.

What is "20dfc4e46c7b7d0a930db3febc76557f" referring to?

**Comment by maxhelias** [comment]
Nothing, it's just a generated string sent to the Flex server

**Comment by ThomasLandauer** [comment]
I have some other projects with `phpstan/extension-installer` that I haven't updated for a while. What can I do to find out where the message is coming from?

**Comment by nicolas-grekas** [comment]
Technically, it refers to a git tree-hash. That represents the state of the recipe when it was installed.
As stated in https://github.com/symfony/recipes/issues/834#issuecomment-714429042, this message is coming from flex, who detected that a package was removed.

Now, if you're asking why it has been removed, I don't know. Flex/recipes don't do that.

I'm closing because this report is based on a wrong assumption ("something killed phpstan/extension-installer" => not a recipe for sure).

**Comment by maxhelias** [comment]
On my project, I got the message only when I made a `composer remove phpstan/extension-installer`.
`composer update` has behavior normally
