### ISSUE TITLE
[lexik/jwt-authentication-bundle] Keys should be git-ignored

### ISSUE THREAD

**Issue by teohhanhui** [symfony/recipes#84]
You certainly do not want to commit these to the repository.

**Comment by davidbarratt** [comment]
Per the installation instructions, they are supposed to be in the `var` directory:
https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/index.md#installation

**Comment by chalasr** [comment]
@davidbarratt I have to update the docs to recommend using confug. See discussion in https://github.com/symfony/recipes/pull/89

**Comment by fabpot** [comment]
Closing this issue as discussion happens on the PR now.
