### ISSUE TITLE
[nelmio/cors-bundle] Malformed shell syntax for CORS_ALLOW_ORIGIN recipe defaults

### ISSUE THREAD

**Issue by yannoff** [symfony/recipes#848]
Here might be the right place for https://github.com/nelmio/NelmioCorsBundle/issues/149 :

The default recipe installs with
`CORS_ALLOW_ORIGIN=^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$`

Which errors when loaded from shell.
```
source ./.env
```
Result
```
./.env: line 48: syntax error near unexpected token `('
./.env: line 48: `CORS_ALLOW_ORIGIN=^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'
```
To resolve the issue, wrap the pattern in double quotes, which will be parsed out by `symfony/dotenv` and be properly configured in `shell`
```
CORS_ALLOW_ORIGIN="^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$"
```

**Comment by OskarStark** [comment]
You have a trailing single quote at the end 🤔

**Comment by yannoff** [comment]
@OskarStark What are you talking about ? The "result" block is the output of the `source` command, bash errors are always formatted this way, nothing to do with the content of the variable

**Comment by yannoff** [comment]
@chalasr @Nyholm Since #849 was merged and released, maybe we can close this one ? :rocket:
