### ISSUE TITLE
[FrameworkBundle] Dotenv with constructor parameter is deprecated

### ISSUE THREAD

**Issue by WouterCypers** [symfony/recipes#869]
**Problem:**
In `config/bootstrap.php`, there are 2 lines (14 and 17) using a boolean constructor argument in `Dotenv`, which is deprecated. I discovered this when running PHPUnit:

> Since symfony/dotenv 5.1: Passing a boolean to the constructor of "Symfony\Component\Dotenv\Dotenv" is deprecated, use "Dotenv::usePutenv()".

**Possible solution:**
Removing the parameter.

Can I just create a pull request? I'm quite new to contributing.

**Comment by xabbuh** [comment]
If I don't miss anything that's only true for the recipes that target Dotenv versions before 5.1. Do I miss anything?

**Comment by nicolas-grekas** [comment]
I confirm what @xabbuh says.
Also, recipes for 5.1+ don't use a `config/bootstrap.php` file anyone, you might want to delete it after syncing your other files.

**Comment by mrpavlikov** [comment]
I've installed `symfony/phpunit-bridge` and I got this message about `tests/bootstrap.php` I guess:

``` 
1x: Since symfony/dotenv 5.1: Passing a boolean to the constructor of "Symfony\Component\Dotenv\Dotenv" is deprecated, use "Dotenv::usePutenv()".
    1x in Dotenv::__construct from Symfony\Component\Dotenv
```

tests/bootsrap.php:

```
<?php

use Symfony\Component\Dotenv\Dotenv;

require dirname(__DIR__).'/vendor/autoload.php';

if (file_exists(dirname(__DIR__).'/config/bootstrap.php')) {
    require dirname(__DIR__).'/config/bootstrap.php';
} elseif (method_exists(Dotenv::class, 'bootEnv')) {
    (new Dotenv())->bootEnv(dirname(__DIR__).'/.env');
}
```

What am I doing wrong? Symfony 5.4, phpunit/bridge 6.0

**Comment by nuryagdym** [comment]
In my case, I was getting this error, although there was no boolean value passed to `Dotenv` constructor in `tests/bootstrap.php`.
It turned out that unit test is using `public/index.php` which loads `config/bootstrap.php`.
Although, in `phpunit.xml.dist` it is configured to use `tests/bootstrap.php` it was not using it:
```xml
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         bootstrap="tests/bootstrap.php"
>
```

**Comment by naitsirch** [comment]
@nicolas-grekas It would be great if symfony flex cleaned up such files which have been created by earlier recipes and become obsolete. Otherwise we end up with several files in a project which aren't needed anymore.
