### ISSUE TITLE
webpack-encore-bundle does not add twig helpers

### ISSUE THREAD

**Issue by garak** [symfony/recipes#896]
I just installed symfony/webpack-encore-bundle and, per its recipe file, a suggestion is displayed telling to "Uncomment the Twig helpers in templates/base.html.twig"
Anyway, no twig helpers were added to my base template (nor I can find anything that should do such action in the recipe)

**Comment by stof** [comment]
well, that's because your base.html.twig file was not created by the latest version of the TwigBundle recipe (which has this commented code)

**Comment by garak** [comment]
So, is it fair that a recipe of a bundle makes assumptions on recipes of a different bundle?

**Comment by stof** [comment]
well, a recipe for a bundle makes an assumption about an official recipe for TwigBundle in order to provide better DX in all new projects.

**Comment by garak** [comment]
But it should take into account the possibility that other bundle can be at a previous version (just like in my case).
I think that the suggestion about helpers should be more open to possibilities (something like "Uncomment the Twig helpers, if present, in templates/base.html.twig")

**Comment by weaverryan** [comment]
> something like "Uncomment the Twig helpers, if present, in templates/base.html.twig"

That's a good proposal 👍
