### ISSUE TITLE
in phpunit recipe 5.3 bin/phpunit fails with phpunit 9.5

### ISSUE THREAD

**Issue by mmarton** [symfony/recipes#936]
Hi!

I'm experimenting with phpunit and just find that in the 5.3 recipe bin/phpunit tries to require vendor/phpunit/phpunit/phpunit.

https://github.com/symfony/recipes/blob/master/symfony/phpunit-bridge/5.3/bin/phpunit#L4

But that fails with:

> Fatal error: strict_types declaration must be the very first statement in the script in /var/www/html/vendor/phpunit/phpunit/phpunit on line 2

looks like importing a file which has booth declare() AND an interpreter (`#!/usr/bin/env `) cannot be imported.
might be a php bug idk

https://github.com/sebastianbergmann/phpunit/blob/9.5/phpunit#L1

tried with phpunit 9.5

**Comment by rmikalkenas** [comment]
Experiencing the same issue. @weaverryan this should be interesting for you as you are the owner of this change.
From my understanding phpunit should have a separate `phpunit.php` which could be used in require statements
