### ISSUE TITLE
Manifest aliases are not working anymore

### ISSUE THREAD

**Issue by t-richard** [symfony/recipes#941]
Someone reported on Slack that the aliases are not working anymore.

Simple reproducer 

```bash
symfony new flex-aliases
cd flex-aliases
composer req orm
```

It should fail with message `"orm" is not a valid alias` but `orm` is a valid alias https://github.com/symfony/recipes/blob/master/symfony/orm-pack/1.0/manifest.json

The list generated at https://flex.symfony.com/aliases.json doesn't contain the alias but seem to contain other aliases that are probably generated from the package name and are not listed in the manifest : `orm-pack` and `ormpack` but it doesn't reference the ones from the recipe.

**Comment by nicodmf** [comment]
same problem here https://github.com/api-platform/core/issues/4259

**Comment by fabpot** [comment]
I'm on it, deploying right now.

**Comment by fabpot** [comment]
Fixed now
