### ISSUE TITLE
Swiftmailer default URL

### ISSUE THREAD

**Issue by yann-eugone** [symfony/recipes#95]
Regarding the [Swiftmailer manifest](https://github.com/symfony/recipes/blob/master/symfony/swiftmailer-bundle/2.5/manifest.json) the default value of the `MAILER_URL` parameter is `smtp://localhost:25?encryption=&auth_mode=`.

Which is an invalid url. I got the following exception : `The  encryption is not supported` (note the double space between The & encryption)

Regarding of [`Symfony\Bundle\SwiftmailerBundle\DependencyInjection\SwiftmailerTransportFactory`](https://github.com/symfony/swiftmailer-bundle/blob/master/DependencyInjection/SwiftmailerTransportFactory.php) I found that the URL query part is parsed with `parse_str` and the values are added one after the other without trying to convert it.

We may have 2 strategies here : 

- Modifiy the `resolveOptions` method of `SwiftmailerTransportFactory` to replace empty string with null
- Modify the value of the `MAILER_URL` parameter in the manifest, and remove these parameters

**Comment by javiereguiluz** [comment]
@yann-eugone thanks for reporting this and for investigating a possible solution. Fabien agreed to fix this in the bundle, so I've opened an issue there: https://github.com/symfony/swiftmailer-bundle/issues/186  I'm closing this then. Thanks!

**Comment by yann-eugone** [comment]
Glad to read this
