### ISSUE TITLE
[DoctrineBundle] Expose port 5432 by default in manifest.json

### ISSUE THREAD

**Issue by Kreyu** [symfony/recipes#960]
Currently, following section is added to `docker-compose.override.yml` for DoctrineBundle:

```
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###
```

With that configuration, it's not possible (I guess?) to connect to database using, for example, a PhpStorm:

```
[08001] Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
```

This is because port 5432 is not exposed if I understand properly. If we manually do something like this, connection is estabilished:

```
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432:5432"
###< doctrine/doctrine-bundle ###
```

Is there any reason why the port is not exposed by default? Should the user do it manually?

https://github.com/symfony/recipes/blob/master/doctrine/doctrine-bundle/2.4/manifest.json#L44

**Comment by weaverryan** [comment]
Ping @dunglas

**Comment by dunglas** [comment]
This configuration exposes the DBMS on a random port. IIRC correctly, this behavior is required by Symfony CLI to be able to run multiple projects at the same time. ping @fabpot

**Comment by dunglas** [comment]
You can use `docker inspect` to find the assigned port. But I agree that it's not convenient when using PHPStorm.

**Comment by Kreyu** [comment]
> This configuration exposes the DBMS on a random port. IIRC correctly, this behavior is required by Symfony CLI to be able to run multiple projects at the same time.

Oh, I didn't notice that. Makes sense.
