### ISSUE TITLE
Add bin/phpunit to .gitignore?

### ISSUE THREAD

**Issue by alh4810** [symfony/recipes#961]
Hello,

I installed phpunit as follows:
`composer require --dev phpunit/phpunit symfony/test-pack`

In Git, I'm seeing an untracked file named bin/phpunit:
```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	bin/phpunit
```

Should I add this file to version control?

I'm only requiring phpunit in my development environment not production. So why commit this to version control? Perhaps for others who choose to install phpunit without the "--dev" flag, it makes more sense to add it to version control, but not for me.

Perhaps the recipe can be updated to automatically add bin/phpunit to .gitignore depending on whether environment is "dev" or "prod"?

**Comment by stof** [comment]
What is the content of this file ? Is it the composer-installed script or is it a file created by the recipe ?

**Comment by alh4810** [comment]
@stof Seems to just be a bash file that calls phpunit from vendor directory.

```
#!/usr/bin/env php
<?php

if (!ini_get('date.timezone')) {
    ini_set('date.timezone', 'UTC');
}

if (is_file(dirname(__DIR__).'/vendor/phpunit/phpunit/phpunit')) {
    define('PHPUNIT_COMPOSER_INSTALL', dirname(__DIR__).'/vendor/autoload.php');
    require PHPUNIT_COMPOSER_INSTALL;
    PHPUnit\TextUI\Command::main();
} else {
    if (!is_file(dirname(__DIR__).'/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php')) {
        echo "Unable to find the `simple-phpunit.php` script in `vendor/symfony/phpunit-bridge/bin/`.\n";
        exit(1);
    }

    require dirname(__DIR__).'/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php';
}
```

I am unsure whether this was created by composer or created by the recipe. I ended up just committing it to version control, even though it will not be needed in production. I feel it is better for me (at this point in my Symfony knowledge) to follow Symfony's .gitignore sane default's even if I feel they don't make perfect sense to me right now.


Also, I don't think it would be that easy to ignore this dynamically. Not a huge issue, but just something I found odd and wanted to bring up to the project.

**Comment by stof** [comment]
this file is a PHP file (not a bash one) create by the recipe. It is not the one created by composer. If you don't commit the file created by the recipe, it won't be recreated for other devs.

**Comment by alh4810** [comment]
@stof That's fair. And you're right, it is PHP. Just found it strange that it wasn't ignored automatically despite using "composer require --dev". Alright, so I'll take that suggestion. I'll un-commit it from version control and add it to .gitignore so that production is slightly more clean.
