### ISSUE TITLE
Packs must never add/modify files in a project

### ISSUE THREAD

**Issue by fabpot** [symfony/recipes#988]
As we always unpack packs now and because we are using Composer to uninstall the pack, the recipes are removed automatically by the Composer plugin/hooks.

It means that a pack CANNOT have anything in the recipes that modifies the local files, so env var, so file creation, ...
In any case, even if we would want to "fix" that, it's not worth it as we are losing the reference to the pack in `symfony.lock`, so we won't be able to update the files whenever the recipe changes.

So, I propose to document that new rule: a pack cannot modify the local filesystem in a recipe and add a corresponding Github action check to ensure nobody tries that.

For existing packs that break this new rule, we must find other ways. The simplest way is to create an empty package with an attached recipe that is required in the pack.

**Comment by greg0ire** [comment]
@nicolas-grekas I'm deferring to @VincentLanglet regarding the Sonata repos. Can you please answer his last question?

**Comment by VincentLanglet** [comment]
I would go with the removal of 
 sonata-project/media-orm-meta
 sonata-project/media-odm-meta
 sonata-project/notification-orm-meta
Because we don't maintain them. They don't even install Sonata 4, but still Sonata 3.

But I'd like confirmation from @nicolas-grekas that removing them from https://github.com/symfony/recipes-contrib/tree/master/sonata-project is enough.

**Comment by nicolas-grekas** [comment]
> Just removing the *-pack recipe in [https://github.com/symfony/recipes-contrib/tree/master/sonata-project](https://github.com/symfony/recipes-contrib/tree/master/sonata-project?rgh-link-date=2021-08-27T20%3A53%3A54Z) and marking the pack as abandoned in the composer.json ?

I confirm that yes!

**Comment by VincentLanglet** [comment]
Done then https://github.com/symfony/recipes-contrib/pull/1357

**Comment by makasim** [comment]
Dont wait for me personally. Someone has to do PR. I'll merge.
